// Code generated by ent, DO NOT EDIT.

package paymentwebhookdelivery

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentwebhookdelivery type in the database.
	Label = "payment_webhook_delivery"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProviderKey holds the string denoting the provider_key field in the database.
	FieldProviderKey = "provider_key"
	// FieldDeliveryID holds the string denoting the delivery_id field in the database.
	FieldDeliveryID = "delivery_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldTestNotification holds the string denoting the test_notification field in the database.
	FieldTestNotification = "test_notification"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRawBodyHash holds the string denoting the raw_body_hash field in the database.
	FieldRawBodyHash = "raw_body_hash"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldReceivedAt holds the string denoting the received_at field in the database.
	FieldReceivedAt = "received_at"
	// FieldProcessedAt holds the string denoting the processed_at field in the database.
	FieldProcessedAt = "processed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the paymentwebhookdelivery in the database.
	Table = "payment_webhook_deliveries"
)

// Columns holds all SQL columns for paymentwebhookdelivery fields.
var Columns = []string{
	FieldID,
	FieldProviderKey,
	FieldDeliveryID,
	FieldEventType,
	FieldTestNotification,
	FieldStatus,
	FieldRawBodyHash,
	FieldError,
	FieldReceivedAt,
	FieldProcessedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderKeyValidator is a validator for the "provider_key" field. It is called by the builders before save.
	ProviderKeyValidator func(string) error
	// DeliveryIDValidator is a validator for the "delivery_id" field. It is called by the builders before save.
	DeliveryIDValidator func(string) error
	// DefaultEventType holds the default value on creation for the "event_type" field.
	DefaultEventType string
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultTestNotification holds the default value on creation for the "test_notification" field.
	DefaultTestNotification bool
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultRawBodyHash holds the default value on creation for the "raw_body_hash" field.
	DefaultRawBodyHash string
	// RawBodyHashValidator is a validator for the "raw_body_hash" field. It is called by the builders before save.
	RawBodyHashValidator func(string) error
	// DefaultReceivedAt holds the default value on creation for the "received_at" field.
	DefaultReceivedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentWebhookDelivery queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProviderKey orders the results by the provider_key field.
func ByProviderKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderKey, opts...).ToFunc()
}

// ByDeliveryID orders the results by the delivery_id field.
func ByDeliveryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByTestNotification orders the results by the test_notification field.
func ByTestNotification(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTestNotification, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRawBodyHash orders the results by the raw_body_hash field.
func ByRawBodyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawBodyHash, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByReceivedAt orders the results by the received_at field.
func ByReceivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivedAt, opts...).ToFunc()
}

// ByProcessedAt orders the results by the processed_at field.
func ByProcessedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
