// Code generated by ent, DO NOT EDIT.

package paymentwebhookdelivery

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLTE(FieldID, id))
}

// ProviderKey applies equality check predicate on the "provider_key" field. It's identical to ProviderKeyEQ.
func ProviderKey(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldProviderKey, v))
}

// DeliveryID applies equality check predicate on the "delivery_id" field. It's identical to DeliveryIDEQ.
func DeliveryID(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldDeliveryID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldEventType, v))
}

// TestNotification applies equality check predicate on the "test_notification" field. It's identical to TestNotificationEQ.
func TestNotification(v bool) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldTestNotification, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldStatus, v))
}

// RawBodyHash applies equality check predicate on the "raw_body_hash" field. It's identical to RawBodyHashEQ.
func RawBodyHash(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldRawBodyHash, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldError, v))
}

// ReceivedAt applies equality check predicate on the "received_at" field. It's identical to ReceivedAtEQ.
func ReceivedAt(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldReceivedAt, v))
}

// ProcessedAt applies equality check predicate on the "processed_at" field. It's identical to ProcessedAtEQ.
func ProcessedAt(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldProcessedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderKeyEQ applies the EQ predicate on the "provider_key" field.
func ProviderKeyEQ(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldProviderKey, v))
}

// ProviderKeyNEQ applies the NEQ predicate on the "provider_key" field.
func ProviderKeyNEQ(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNEQ(FieldProviderKey, v))
}

// ProviderKeyIn applies the In predicate on the "provider_key" field.
func ProviderKeyIn(vs ...string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIn(FieldProviderKey, vs...))
}

// ProviderKeyNotIn applies the NotIn predicate on the "provider_key" field.
func ProviderKeyNotIn(vs ...string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotIn(FieldProviderKey, vs...))
}

// ProviderKeyGT applies the GT predicate on the "provider_key" field.
func ProviderKeyGT(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGT(FieldProviderKey, v))
}

// ProviderKeyGTE applies the GTE predicate on the "provider_key" field.
func ProviderKeyGTE(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGTE(FieldProviderKey, v))
}

// ProviderKeyLT applies the LT predicate on the "provider_key" field.
func ProviderKeyLT(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLT(FieldProviderKey, v))
}

// ProviderKeyLTE applies the LTE predicate on the "provider_key" field.
func ProviderKeyLTE(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLTE(FieldProviderKey, v))
}

// ProviderKeyContains applies the Contains predicate on the "provider_key" field.
func ProviderKeyContains(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldContains(FieldProviderKey, v))
}

// ProviderKeyHasPrefix applies the HasPrefix predicate on the "provider_key" field.
func ProviderKeyHasPrefix(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldHasPrefix(FieldProviderKey, v))
}

// ProviderKeyHasSuffix applies the HasSuffix predicate on the "provider_key" field.
func ProviderKeyHasSuffix(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldHasSuffix(FieldProviderKey, v))
}

// ProviderKeyEqualFold applies the EqualFold predicate on the "provider_key" field.
func ProviderKeyEqualFold(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEqualFold(FieldProviderKey, v))
}

// ProviderKeyContainsFold applies the ContainsFold predicate on the "provider_key" field.
func ProviderKeyContainsFold(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldContainsFold(FieldProviderKey, v))
}

// DeliveryIDEQ applies the EQ predicate on the "delivery_id" field.
func DeliveryIDEQ(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldDeliveryID, v))
}

// DeliveryIDNEQ applies the NEQ predicate on the "delivery_id" field.
func DeliveryIDNEQ(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNEQ(FieldDeliveryID, v))
}

// DeliveryIDIn applies the In predicate on the "delivery_id" field.
func DeliveryIDIn(vs ...string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIn(FieldDeliveryID, vs...))
}

// DeliveryIDNotIn applies the NotIn predicate on the "delivery_id" field.
func DeliveryIDNotIn(vs ...string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotIn(FieldDeliveryID, vs...))
}

// DeliveryIDGT applies the GT predicate on the "delivery_id" field.
func DeliveryIDGT(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGT(FieldDeliveryID, v))
}

// DeliveryIDGTE applies the GTE predicate on the "delivery_id" field.
func DeliveryIDGTE(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGTE(FieldDeliveryID, v))
}

// DeliveryIDLT applies the LT predicate on the "delivery_id" field.
func DeliveryIDLT(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLT(FieldDeliveryID, v))
}

// DeliveryIDLTE applies the LTE predicate on the "delivery_id" field.
func DeliveryIDLTE(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLTE(FieldDeliveryID, v))
}

// DeliveryIDContains applies the Contains predicate on the "delivery_id" field.
func DeliveryIDContains(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldContains(FieldDeliveryID, v))
}

// DeliveryIDHasPrefix applies the HasPrefix predicate on the "delivery_id" field.
func DeliveryIDHasPrefix(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldHasPrefix(FieldDeliveryID, v))
}

// DeliveryIDHasSuffix applies the HasSuffix predicate on the "delivery_id" field.
func DeliveryIDHasSuffix(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldHasSuffix(FieldDeliveryID, v))
}

// DeliveryIDEqualFold applies the EqualFold predicate on the "delivery_id" field.
func DeliveryIDEqualFold(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEqualFold(FieldDeliveryID, v))
}

// DeliveryIDContainsFold applies the ContainsFold predicate on the "delivery_id" field.
func DeliveryIDContainsFold(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldContainsFold(FieldDeliveryID, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldContainsFold(FieldEventType, v))
}

// TestNotificationEQ applies the EQ predicate on the "test_notification" field.
func TestNotificationEQ(v bool) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldTestNotification, v))
}

// TestNotificationNEQ applies the NEQ predicate on the "test_notification" field.
func TestNotificationNEQ(v bool) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNEQ(FieldTestNotification, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldContainsFold(FieldStatus, v))
}

// RawBodyHashEQ applies the EQ predicate on the "raw_body_hash" field.
func RawBodyHashEQ(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldRawBodyHash, v))
}

// RawBodyHashNEQ applies the NEQ predicate on the "raw_body_hash" field.
func RawBodyHashNEQ(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNEQ(FieldRawBodyHash, v))
}

// RawBodyHashIn applies the In predicate on the "raw_body_hash" field.
func RawBodyHashIn(vs ...string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIn(FieldRawBodyHash, vs...))
}

// RawBodyHashNotIn applies the NotIn predicate on the "raw_body_hash" field.
func RawBodyHashNotIn(vs ...string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotIn(FieldRawBodyHash, vs...))
}

// RawBodyHashGT applies the GT predicate on the "raw_body_hash" field.
func RawBodyHashGT(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGT(FieldRawBodyHash, v))
}

// RawBodyHashGTE applies the GTE predicate on the "raw_body_hash" field.
func RawBodyHashGTE(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGTE(FieldRawBodyHash, v))
}

// RawBodyHashLT applies the LT predicate on the "raw_body_hash" field.
func RawBodyHashLT(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLT(FieldRawBodyHash, v))
}

// RawBodyHashLTE applies the LTE predicate on the "raw_body_hash" field.
func RawBodyHashLTE(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLTE(FieldRawBodyHash, v))
}

// RawBodyHashContains applies the Contains predicate on the "raw_body_hash" field.
func RawBodyHashContains(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldContains(FieldRawBodyHash, v))
}

// RawBodyHashHasPrefix applies the HasPrefix predicate on the "raw_body_hash" field.
func RawBodyHashHasPrefix(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldHasPrefix(FieldRawBodyHash, v))
}

// RawBodyHashHasSuffix applies the HasSuffix predicate on the "raw_body_hash" field.
func RawBodyHashHasSuffix(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldHasSuffix(FieldRawBodyHash, v))
}

// RawBodyHashEqualFold applies the EqualFold predicate on the "raw_body_hash" field.
func RawBodyHashEqualFold(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEqualFold(FieldRawBodyHash, v))
}

// RawBodyHashContainsFold applies the ContainsFold predicate on the "raw_body_hash" field.
func RawBodyHashContainsFold(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldContainsFold(FieldRawBodyHash, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldContainsFold(FieldError, v))
}

// ReceivedAtEQ applies the EQ predicate on the "received_at" field.
func ReceivedAtEQ(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldReceivedAt, v))
}

// ReceivedAtNEQ applies the NEQ predicate on the "received_at" field.
func ReceivedAtNEQ(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNEQ(FieldReceivedAt, v))
}

// ReceivedAtIn applies the In predicate on the "received_at" field.
func ReceivedAtIn(vs ...time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIn(FieldReceivedAt, vs...))
}

// ReceivedAtNotIn applies the NotIn predicate on the "received_at" field.
func ReceivedAtNotIn(vs ...time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotIn(FieldReceivedAt, vs...))
}

// ReceivedAtGT applies the GT predicate on the "received_at" field.
func ReceivedAtGT(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGT(FieldReceivedAt, v))
}

// ReceivedAtGTE applies the GTE predicate on the "received_at" field.
func ReceivedAtGTE(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGTE(FieldReceivedAt, v))
}

// ReceivedAtLT applies the LT predicate on the "received_at" field.
func ReceivedAtLT(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLT(FieldReceivedAt, v))
}

// ReceivedAtLTE applies the LTE predicate on the "received_at" field.
func ReceivedAtLTE(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLTE(FieldReceivedAt, v))
}

// ProcessedAtEQ applies the EQ predicate on the "processed_at" field.
func ProcessedAtEQ(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldProcessedAt, v))
}

// ProcessedAtNEQ applies the NEQ predicate on the "processed_at" field.
func ProcessedAtNEQ(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNEQ(FieldProcessedAt, v))
}

// ProcessedAtIn applies the In predicate on the "processed_at" field.
func ProcessedAtIn(vs ...time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIn(FieldProcessedAt, vs...))
}

// ProcessedAtNotIn applies the NotIn predicate on the "processed_at" field.
func ProcessedAtNotIn(vs ...time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotIn(FieldProcessedAt, vs...))
}

// ProcessedAtGT applies the GT predicate on the "processed_at" field.
func ProcessedAtGT(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGT(FieldProcessedAt, v))
}

// ProcessedAtGTE applies the GTE predicate on the "processed_at" field.
func ProcessedAtGTE(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGTE(FieldProcessedAt, v))
}

// ProcessedAtLT applies the LT predicate on the "processed_at" field.
func ProcessedAtLT(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLT(FieldProcessedAt, v))
}

// ProcessedAtLTE applies the LTE predicate on the "processed_at" field.
func ProcessedAtLTE(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLTE(FieldProcessedAt, v))
}

// ProcessedAtIsNil applies the IsNil predicate on the "processed_at" field.
func ProcessedAtIsNil() predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIsNull(FieldProcessedAt))
}

// ProcessedAtNotNil applies the NotNil predicate on the "processed_at" field.
func ProcessedAtNotNil() predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotNull(FieldProcessedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentWebhookDelivery) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentWebhookDelivery) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentWebhookDelivery) predicate.PaymentWebhookDelivery {
	return predicate.PaymentWebhookDelivery(sql.NotPredicates(p))
}
