// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelpriceoverride"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelPriceOverrideUpdate is the builder for updating ModelPriceOverride entities.
type ModelPriceOverrideUpdate struct {
	config
	hooks    []Hook
	mutation *ModelPriceOverrideMutation
}

// Where appends a list predicates to the ModelPriceOverrideUpdate builder.
func (_u *ModelPriceOverrideUpdate) Where(ps ...predicate.ModelPriceOverride) *ModelPriceOverrideUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelPriceOverrideUpdate) SetUpdatedAt(v time.Time) *ModelPriceOverrideUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ModelPriceOverrideUpdate) SetPlatform(v string) *ModelPriceOverrideUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillablePlatform(v *string) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *ModelPriceOverrideUpdate) SetModelName(v string) *ModelPriceOverrideUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableModelName(v *string) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ModelPriceOverrideUpdate) SetCurrency(v modelpriceoverride.Currency) *ModelPriceOverrideUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableCurrency(v *modelpriceoverride.Currency) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *ModelPriceOverrideUpdate) SetPayload(v map[string]interface{}) *ModelPriceOverrideUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *ModelPriceOverrideUpdate) ClearPayload() *ModelPriceOverrideUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ModelPriceOverrideUpdate) SetEnabled(v bool) *ModelPriceOverrideUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableEnabled(v *bool) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *ModelPriceOverrideUpdate) SetNote(v string) *ModelPriceOverrideUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableNote(v *string) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *ModelPriceOverrideUpdate) ClearNote() *ModelPriceOverrideUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ModelPriceOverrideUpdate) SetUpdatedBy(v int64) *ModelPriceOverrideUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdate) SetNillableUpdatedBy(v *int64) *ModelPriceOverrideUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ModelPriceOverrideUpdate) AddUpdatedBy(v int64) *ModelPriceOverrideUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ModelPriceOverrideUpdate) ClearUpdatedBy() *ModelPriceOverrideUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// Mutation returns the ModelPriceOverrideMutation object of the builder.
func (_u *ModelPriceOverrideUpdate) Mutation() *ModelPriceOverrideMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelPriceOverrideUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPriceOverrideUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelPriceOverrideUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPriceOverrideUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelPriceOverrideUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelpriceoverride.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelPriceOverrideUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := modelpriceoverride.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelName(); ok {
		if err := modelpriceoverride.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.model_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := modelpriceoverride.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.currency": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelPriceOverrideUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelpriceoverride.Table, modelpriceoverride.Columns, sqlgraph.NewFieldSpec(modelpriceoverride.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpriceoverride.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(modelpriceoverride.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(modelpriceoverride.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(modelpriceoverride.FieldCurrency, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(modelpriceoverride.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(modelpriceoverride.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(modelpriceoverride.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(modelpriceoverride.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(modelpriceoverride.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpriceoverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelPriceOverrideUpdateOne is the builder for updating a single ModelPriceOverride entity.
type ModelPriceOverrideUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelPriceOverrideMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelPriceOverrideUpdateOne) SetUpdatedAt(v time.Time) *ModelPriceOverrideUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ModelPriceOverrideUpdateOne) SetPlatform(v string) *ModelPriceOverrideUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillablePlatform(v *string) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *ModelPriceOverrideUpdateOne) SetModelName(v string) *ModelPriceOverrideUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableModelName(v *string) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ModelPriceOverrideUpdateOne) SetCurrency(v modelpriceoverride.Currency) *ModelPriceOverrideUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableCurrency(v *modelpriceoverride.Currency) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *ModelPriceOverrideUpdateOne) SetPayload(v map[string]interface{}) *ModelPriceOverrideUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *ModelPriceOverrideUpdateOne) ClearPayload() *ModelPriceOverrideUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ModelPriceOverrideUpdateOne) SetEnabled(v bool) *ModelPriceOverrideUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableEnabled(v *bool) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *ModelPriceOverrideUpdateOne) SetNote(v string) *ModelPriceOverrideUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableNote(v *string) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *ModelPriceOverrideUpdateOne) ClearNote() *ModelPriceOverrideUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ModelPriceOverrideUpdateOne) SetUpdatedBy(v int64) *ModelPriceOverrideUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ModelPriceOverrideUpdateOne) SetNillableUpdatedBy(v *int64) *ModelPriceOverrideUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *ModelPriceOverrideUpdateOne) AddUpdatedBy(v int64) *ModelPriceOverrideUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ModelPriceOverrideUpdateOne) ClearUpdatedBy() *ModelPriceOverrideUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// Mutation returns the ModelPriceOverrideMutation object of the builder.
func (_u *ModelPriceOverrideUpdateOne) Mutation() *ModelPriceOverrideMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelPriceOverrideUpdate builder.
func (_u *ModelPriceOverrideUpdateOne) Where(ps ...predicate.ModelPriceOverride) *ModelPriceOverrideUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelPriceOverrideUpdateOne) Select(field string, fields ...string) *ModelPriceOverrideUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelPriceOverride entity.
func (_u *ModelPriceOverrideUpdateOne) Save(ctx context.Context) (*ModelPriceOverride, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPriceOverrideUpdateOne) SaveX(ctx context.Context) *ModelPriceOverride {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelPriceOverrideUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPriceOverrideUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelPriceOverrideUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelpriceoverride.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelPriceOverrideUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := modelpriceoverride.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelName(); ok {
		if err := modelpriceoverride.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.model_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := modelpriceoverride.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.currency": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelPriceOverrideUpdateOne) sqlSave(ctx context.Context) (_node *ModelPriceOverride, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelpriceoverride.Table, modelpriceoverride.Columns, sqlgraph.NewFieldSpec(modelpriceoverride.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelPriceOverride.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelpriceoverride.FieldID)
		for _, f := range fields {
			if !modelpriceoverride.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelpriceoverride.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpriceoverride.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(modelpriceoverride.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(modelpriceoverride.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(modelpriceoverride.FieldCurrency, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(modelpriceoverride.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(modelpriceoverride.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(modelpriceoverride.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(modelpriceoverride.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(modelpriceoverride.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64)
	}
	_node = &ModelPriceOverride{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpriceoverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
