// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelpriceoverride"
)

// ModelPriceOverrideCreate is the builder for creating a ModelPriceOverride entity.
type ModelPriceOverrideCreate struct {
	config
	mutation *ModelPriceOverrideMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelPriceOverrideCreate) SetCreatedAt(v time.Time) *ModelPriceOverrideCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableCreatedAt(v *time.Time) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelPriceOverrideCreate) SetUpdatedAt(v time.Time) *ModelPriceOverrideCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableUpdatedAt(v *time.Time) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *ModelPriceOverrideCreate) SetPlatform(v string) *ModelPriceOverrideCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetModelName sets the "model_name" field.
func (_c *ModelPriceOverrideCreate) SetModelName(v string) *ModelPriceOverrideCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *ModelPriceOverrideCreate) SetCurrency(v modelpriceoverride.Currency) *ModelPriceOverrideCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableCurrency(v *modelpriceoverride.Currency) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *ModelPriceOverrideCreate) SetPayload(v map[string]interface{}) *ModelPriceOverrideCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ModelPriceOverrideCreate) SetEnabled(v bool) *ModelPriceOverrideCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableEnabled(v *bool) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *ModelPriceOverrideCreate) SetNote(v string) *ModelPriceOverrideCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableNote(v *string) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ModelPriceOverrideCreate) SetUpdatedBy(v int64) *ModelPriceOverrideCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ModelPriceOverrideCreate) SetNillableUpdatedBy(v *int64) *ModelPriceOverrideCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// Mutation returns the ModelPriceOverrideMutation object of the builder.
func (_c *ModelPriceOverrideCreate) Mutation() *ModelPriceOverrideMutation {
	return _c.mutation
}

// Save creates the ModelPriceOverride in the database.
func (_c *ModelPriceOverrideCreate) Save(ctx context.Context) (*ModelPriceOverride, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelPriceOverrideCreate) SaveX(ctx context.Context) *ModelPriceOverride {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelPriceOverrideCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelPriceOverrideCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelPriceOverrideCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelpriceoverride.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelpriceoverride.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := modelpriceoverride.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := modelpriceoverride.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelPriceOverrideCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelPriceOverride.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelPriceOverride.updated_at"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "ModelPriceOverride.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := modelpriceoverride.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelName(); !ok {
		return &ValidationError{Name: "model_name", err: errors.New(`ent: missing required field "ModelPriceOverride.model_name"`)}
	}
	if v, ok := _c.mutation.ModelName(); ok {
		if err := modelpriceoverride.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.model_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "ModelPriceOverride.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := modelpriceoverride.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ModelPriceOverride.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ModelPriceOverride.enabled"`)}
	}
	return nil
}

func (_c *ModelPriceOverrideCreate) sqlSave(ctx context.Context) (*ModelPriceOverride, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelPriceOverrideCreate) createSpec() (*ModelPriceOverride, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelPriceOverride{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelpriceoverride.Table, sqlgraph.NewFieldSpec(modelpriceoverride.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelpriceoverride.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpriceoverride.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(modelpriceoverride.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(modelpriceoverride.FieldModelName, field.TypeString, value)
		_node.ModelName = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(modelpriceoverride.FieldCurrency, field.TypeEnum, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(modelpriceoverride.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(modelpriceoverride.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(modelpriceoverride.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(modelpriceoverride.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelPriceOverride.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelPriceOverrideUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelPriceOverrideCreate) OnConflict(opts ...sql.ConflictOption) *ModelPriceOverrideUpsertOne {
	_c.conflict = opts
	return &ModelPriceOverrideUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelPriceOverride.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelPriceOverrideCreate) OnConflictColumns(columns ...string) *ModelPriceOverrideUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelPriceOverrideUpsertOne{
		create: _c,
	}
}

type (
	// ModelPriceOverrideUpsertOne is the builder for "upsert"-ing
	//  one ModelPriceOverride node.
	ModelPriceOverrideUpsertOne struct {
		create *ModelPriceOverrideCreate
	}

	// ModelPriceOverrideUpsert is the "OnConflict" setter.
	ModelPriceOverrideUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelPriceOverrideUpsert) SetUpdatedAt(v time.Time) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateUpdatedAt() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldUpdatedAt)
	return u
}

// SetPlatform sets the "platform" field.
func (u *ModelPriceOverrideUpsert) SetPlatform(v string) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdatePlatform() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldPlatform)
	return u
}

// SetModelName sets the "model_name" field.
func (u *ModelPriceOverrideUpsert) SetModelName(v string) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldModelName, v)
	return u
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateModelName() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldModelName)
	return u
}

// SetCurrency sets the "currency" field.
func (u *ModelPriceOverrideUpsert) SetCurrency(v modelpriceoverride.Currency) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateCurrency() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldCurrency)
	return u
}

// SetPayload sets the "payload" field.
func (u *ModelPriceOverrideUpsert) SetPayload(v map[string]interface{}) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdatePayload() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldPayload)
	return u
}

// ClearPayload clears the value of the "payload" field.
func (u *ModelPriceOverrideUpsert) ClearPayload() *ModelPriceOverrideUpsert {
	u.SetNull(modelpriceoverride.FieldPayload)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ModelPriceOverrideUpsert) SetEnabled(v bool) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateEnabled() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldEnabled)
	return u
}

// SetNote sets the "note" field.
func (u *ModelPriceOverrideUpsert) SetNote(v string) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateNote() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *ModelPriceOverrideUpsert) ClearNote() *ModelPriceOverrideUpsert {
	u.SetNull(modelpriceoverride.FieldNote)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ModelPriceOverrideUpsert) SetUpdatedBy(v int64) *ModelPriceOverrideUpsert {
	u.Set(modelpriceoverride.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsert) UpdateUpdatedBy() *ModelPriceOverrideUpsert {
	u.SetExcluded(modelpriceoverride.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ModelPriceOverrideUpsert) AddUpdatedBy(v int64) *ModelPriceOverrideUpsert {
	u.Add(modelpriceoverride.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ModelPriceOverrideUpsert) ClearUpdatedBy() *ModelPriceOverrideUpsert {
	u.SetNull(modelpriceoverride.FieldUpdatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelPriceOverride.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelPriceOverrideUpsertOne) UpdateNewValues() *ModelPriceOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelpriceoverride.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelPriceOverride.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelPriceOverrideUpsertOne) Ignore() *ModelPriceOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelPriceOverrideUpsertOne) DoNothing() *ModelPriceOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelPriceOverrideCreate.OnConflict
// documentation for more info.
func (u *ModelPriceOverrideUpsertOne) Update(set func(*ModelPriceOverrideUpsert)) *ModelPriceOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelPriceOverrideUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelPriceOverrideUpsertOne) SetUpdatedAt(v time.Time) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateUpdatedAt() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPlatform sets the "platform" field.
func (u *ModelPriceOverrideUpsertOne) SetPlatform(v string) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdatePlatform() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdatePlatform()
	})
}

// SetModelName sets the "model_name" field.
func (u *ModelPriceOverrideUpsertOne) SetModelName(v string) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateModelName() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateModelName()
	})
}

// SetCurrency sets the "currency" field.
func (u *ModelPriceOverrideUpsertOne) SetCurrency(v modelpriceoverride.Currency) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateCurrency() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateCurrency()
	})
}

// SetPayload sets the "payload" field.
func (u *ModelPriceOverrideUpsertOne) SetPayload(v map[string]interface{}) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdatePayload() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *ModelPriceOverrideUpsertOne) ClearPayload() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearPayload()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ModelPriceOverrideUpsertOne) SetEnabled(v bool) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateEnabled() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateEnabled()
	})
}

// SetNote sets the "note" field.
func (u *ModelPriceOverrideUpsertOne) SetNote(v string) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateNote() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *ModelPriceOverrideUpsertOne) ClearNote() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearNote()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ModelPriceOverrideUpsertOne) SetUpdatedBy(v int64) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ModelPriceOverrideUpsertOne) AddUpdatedBy(v int64) *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertOne) UpdateUpdatedBy() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ModelPriceOverrideUpsertOne) ClearUpdatedBy() *ModelPriceOverrideUpsertOne {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearUpdatedBy()
	})
}

// Exec executes the query.
func (u *ModelPriceOverrideUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelPriceOverrideCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelPriceOverrideUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelPriceOverrideUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelPriceOverrideUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelPriceOverrideCreateBulk is the builder for creating many ModelPriceOverride entities in bulk.
type ModelPriceOverrideCreateBulk struct {
	config
	err      error
	builders []*ModelPriceOverrideCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelPriceOverride entities in the database.
func (_c *ModelPriceOverrideCreateBulk) Save(ctx context.Context) ([]*ModelPriceOverride, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelPriceOverride, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelPriceOverrideMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelPriceOverrideCreateBulk) SaveX(ctx context.Context) []*ModelPriceOverride {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelPriceOverrideCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelPriceOverrideCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelPriceOverride.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelPriceOverrideUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelPriceOverrideCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelPriceOverrideUpsertBulk {
	_c.conflict = opts
	return &ModelPriceOverrideUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelPriceOverride.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelPriceOverrideCreateBulk) OnConflictColumns(columns ...string) *ModelPriceOverrideUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelPriceOverrideUpsertBulk{
		create: _c,
	}
}

// ModelPriceOverrideUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelPriceOverride nodes.
type ModelPriceOverrideUpsertBulk struct {
	create *ModelPriceOverrideCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelPriceOverride.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelPriceOverrideUpsertBulk) UpdateNewValues() *ModelPriceOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelpriceoverride.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelPriceOverride.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelPriceOverrideUpsertBulk) Ignore() *ModelPriceOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelPriceOverrideUpsertBulk) DoNothing() *ModelPriceOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelPriceOverrideCreateBulk.OnConflict
// documentation for more info.
func (u *ModelPriceOverrideUpsertBulk) Update(set func(*ModelPriceOverrideUpsert)) *ModelPriceOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelPriceOverrideUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelPriceOverrideUpsertBulk) SetUpdatedAt(v time.Time) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateUpdatedAt() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPlatform sets the "platform" field.
func (u *ModelPriceOverrideUpsertBulk) SetPlatform(v string) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdatePlatform() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdatePlatform()
	})
}

// SetModelName sets the "model_name" field.
func (u *ModelPriceOverrideUpsertBulk) SetModelName(v string) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateModelName() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateModelName()
	})
}

// SetCurrency sets the "currency" field.
func (u *ModelPriceOverrideUpsertBulk) SetCurrency(v modelpriceoverride.Currency) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateCurrency() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateCurrency()
	})
}

// SetPayload sets the "payload" field.
func (u *ModelPriceOverrideUpsertBulk) SetPayload(v map[string]interface{}) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdatePayload() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *ModelPriceOverrideUpsertBulk) ClearPayload() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearPayload()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ModelPriceOverrideUpsertBulk) SetEnabled(v bool) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateEnabled() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateEnabled()
	})
}

// SetNote sets the "note" field.
func (u *ModelPriceOverrideUpsertBulk) SetNote(v string) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateNote() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *ModelPriceOverrideUpsertBulk) ClearNote() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearNote()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ModelPriceOverrideUpsertBulk) SetUpdatedBy(v int64) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ModelPriceOverrideUpsertBulk) AddUpdatedBy(v int64) *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ModelPriceOverrideUpsertBulk) UpdateUpdatedBy() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ModelPriceOverrideUpsertBulk) ClearUpdatedBy() *ModelPriceOverrideUpsertBulk {
	return u.Update(func(s *ModelPriceOverrideUpsert) {
		s.ClearUpdatedBy()
	})
}

// Exec executes the query.
func (u *ModelPriceOverrideUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelPriceOverrideCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelPriceOverrideCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelPriceOverrideUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
