// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentwebhookdelivery"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentWebhookDeliveryUpdate is the builder for updating PaymentWebhookDelivery entities.
type PaymentWebhookDeliveryUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentWebhookDeliveryMutation
}

// Where appends a list predicates to the PaymentWebhookDeliveryUpdate builder.
func (_u *PaymentWebhookDeliveryUpdate) Where(ps ...predicate.PaymentWebhookDelivery) *PaymentWebhookDeliveryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderKey sets the "provider_key" field.
func (_u *PaymentWebhookDeliveryUpdate) SetProviderKey(v string) *PaymentWebhookDeliveryUpdate {
	_u.mutation.SetProviderKey(v)
	return _u
}

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdate) SetNillableProviderKey(v *string) *PaymentWebhookDeliveryUpdate {
	if v != nil {
		_u.SetProviderKey(*v)
	}
	return _u
}

// SetDeliveryID sets the "delivery_id" field.
func (_u *PaymentWebhookDeliveryUpdate) SetDeliveryID(v string) *PaymentWebhookDeliveryUpdate {
	_u.mutation.SetDeliveryID(v)
	return _u
}

// SetNillableDeliveryID sets the "delivery_id" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdate) SetNillableDeliveryID(v *string) *PaymentWebhookDeliveryUpdate {
	if v != nil {
		_u.SetDeliveryID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *PaymentWebhookDeliveryUpdate) SetEventType(v string) *PaymentWebhookDeliveryUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdate) SetNillableEventType(v *string) *PaymentWebhookDeliveryUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetTestNotification sets the "test_notification" field.
func (_u *PaymentWebhookDeliveryUpdate) SetTestNotification(v bool) *PaymentWebhookDeliveryUpdate {
	_u.mutation.SetTestNotification(v)
	return _u
}

// SetNillableTestNotification sets the "test_notification" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdate) SetNillableTestNotification(v *bool) *PaymentWebhookDeliveryUpdate {
	if v != nil {
		_u.SetTestNotification(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentWebhookDeliveryUpdate) SetStatus(v string) *PaymentWebhookDeliveryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdate) SetNillableStatus(v *string) *PaymentWebhookDeliveryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRawBodyHash sets the "raw_body_hash" field.
func (_u *PaymentWebhookDeliveryUpdate) SetRawBodyHash(v string) *PaymentWebhookDeliveryUpdate {
	_u.mutation.SetRawBodyHash(v)
	return _u
}

// SetNillableRawBodyHash sets the "raw_body_hash" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdate) SetNillableRawBodyHash(v *string) *PaymentWebhookDeliveryUpdate {
	if v != nil {
		_u.SetRawBodyHash(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *PaymentWebhookDeliveryUpdate) SetError(v string) *PaymentWebhookDeliveryUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdate) SetNillableError(v *string) *PaymentWebhookDeliveryUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *PaymentWebhookDeliveryUpdate) ClearError() *PaymentWebhookDeliveryUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetReceivedAt sets the "received_at" field.
func (_u *PaymentWebhookDeliveryUpdate) SetReceivedAt(v time.Time) *PaymentWebhookDeliveryUpdate {
	_u.mutation.SetReceivedAt(v)
	return _u
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdate) SetNillableReceivedAt(v *time.Time) *PaymentWebhookDeliveryUpdate {
	if v != nil {
		_u.SetReceivedAt(*v)
	}
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *PaymentWebhookDeliveryUpdate) SetProcessedAt(v time.Time) *PaymentWebhookDeliveryUpdate {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdate) SetNillableProcessedAt(v *time.Time) *PaymentWebhookDeliveryUpdate {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *PaymentWebhookDeliveryUpdate) ClearProcessedAt() *PaymentWebhookDeliveryUpdate {
	_u.mutation.ClearProcessedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentWebhookDeliveryUpdate) SetUpdatedAt(v time.Time) *PaymentWebhookDeliveryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentWebhookDeliveryMutation object of the builder.
func (_u *PaymentWebhookDeliveryUpdate) Mutation() *PaymentWebhookDeliveryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentWebhookDeliveryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentWebhookDeliveryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentWebhookDeliveryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentWebhookDeliveryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentWebhookDeliveryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentwebhookdelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentWebhookDeliveryUpdate) check() error {
	if v, ok := _u.mutation.ProviderKey(); ok {
		if err := paymentwebhookdelivery.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.provider_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryID(); ok {
		if err := paymentwebhookdelivery.DeliveryIDValidator(v); err != nil {
			return &ValidationError{Name: "delivery_id", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.delivery_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := paymentwebhookdelivery.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentwebhookdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RawBodyHash(); ok {
		if err := paymentwebhookdelivery.RawBodyHashValidator(v); err != nil {
			return &ValidationError{Name: "raw_body_hash", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.raw_body_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentWebhookDeliveryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentwebhookdelivery.Table, paymentwebhookdelivery.Columns, sqlgraph.NewFieldSpec(paymentwebhookdelivery.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderKey(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldProviderKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryID(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldDeliveryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TestNotification(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldTestNotification, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawBodyHash(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldRawBodyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(paymentwebhookdelivery.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.ReceivedAt(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldReceivedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(paymentwebhookdelivery.FieldProcessedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentwebhookdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentWebhookDeliveryUpdateOne is the builder for updating a single PaymentWebhookDelivery entity.
type PaymentWebhookDeliveryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentWebhookDeliveryMutation
}

// SetProviderKey sets the "provider_key" field.
func (_u *PaymentWebhookDeliveryUpdateOne) SetProviderKey(v string) *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.SetProviderKey(v)
	return _u
}

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdateOne) SetNillableProviderKey(v *string) *PaymentWebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetProviderKey(*v)
	}
	return _u
}

// SetDeliveryID sets the "delivery_id" field.
func (_u *PaymentWebhookDeliveryUpdateOne) SetDeliveryID(v string) *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.SetDeliveryID(v)
	return _u
}

// SetNillableDeliveryID sets the "delivery_id" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdateOne) SetNillableDeliveryID(v *string) *PaymentWebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetDeliveryID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *PaymentWebhookDeliveryUpdateOne) SetEventType(v string) *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdateOne) SetNillableEventType(v *string) *PaymentWebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetTestNotification sets the "test_notification" field.
func (_u *PaymentWebhookDeliveryUpdateOne) SetTestNotification(v bool) *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.SetTestNotification(v)
	return _u
}

// SetNillableTestNotification sets the "test_notification" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdateOne) SetNillableTestNotification(v *bool) *PaymentWebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetTestNotification(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentWebhookDeliveryUpdateOne) SetStatus(v string) *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdateOne) SetNillableStatus(v *string) *PaymentWebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRawBodyHash sets the "raw_body_hash" field.
func (_u *PaymentWebhookDeliveryUpdateOne) SetRawBodyHash(v string) *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.SetRawBodyHash(v)
	return _u
}

// SetNillableRawBodyHash sets the "raw_body_hash" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdateOne) SetNillableRawBodyHash(v *string) *PaymentWebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetRawBodyHash(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *PaymentWebhookDeliveryUpdateOne) SetError(v string) *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdateOne) SetNillableError(v *string) *PaymentWebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *PaymentWebhookDeliveryUpdateOne) ClearError() *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetReceivedAt sets the "received_at" field.
func (_u *PaymentWebhookDeliveryUpdateOne) SetReceivedAt(v time.Time) *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.SetReceivedAt(v)
	return _u
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdateOne) SetNillableReceivedAt(v *time.Time) *PaymentWebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetReceivedAt(*v)
	}
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *PaymentWebhookDeliveryUpdateOne) SetProcessedAt(v time.Time) *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *PaymentWebhookDeliveryUpdateOne) SetNillableProcessedAt(v *time.Time) *PaymentWebhookDeliveryUpdateOne {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *PaymentWebhookDeliveryUpdateOne) ClearProcessedAt() *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.ClearProcessedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentWebhookDeliveryUpdateOne) SetUpdatedAt(v time.Time) *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentWebhookDeliveryMutation object of the builder.
func (_u *PaymentWebhookDeliveryUpdateOne) Mutation() *PaymentWebhookDeliveryMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentWebhookDeliveryUpdate builder.
func (_u *PaymentWebhookDeliveryUpdateOne) Where(ps ...predicate.PaymentWebhookDelivery) *PaymentWebhookDeliveryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentWebhookDeliveryUpdateOne) Select(field string, fields ...string) *PaymentWebhookDeliveryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentWebhookDelivery entity.
func (_u *PaymentWebhookDeliveryUpdateOne) Save(ctx context.Context) (*PaymentWebhookDelivery, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentWebhookDeliveryUpdateOne) SaveX(ctx context.Context) *PaymentWebhookDelivery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentWebhookDeliveryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentWebhookDeliveryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentWebhookDeliveryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentwebhookdelivery.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentWebhookDeliveryUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderKey(); ok {
		if err := paymentwebhookdelivery.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.provider_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryID(); ok {
		if err := paymentwebhookdelivery.DeliveryIDValidator(v); err != nil {
			return &ValidationError{Name: "delivery_id", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.delivery_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := paymentwebhookdelivery.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentwebhookdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RawBodyHash(); ok {
		if err := paymentwebhookdelivery.RawBodyHashValidator(v); err != nil {
			return &ValidationError{Name: "raw_body_hash", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.raw_body_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentWebhookDeliveryUpdateOne) sqlSave(ctx context.Context) (_node *PaymentWebhookDelivery, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentwebhookdelivery.Table, paymentwebhookdelivery.Columns, sqlgraph.NewFieldSpec(paymentwebhookdelivery.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentWebhookDelivery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentwebhookdelivery.FieldID)
		for _, f := range fields {
			if !paymentwebhookdelivery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentwebhookdelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderKey(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldProviderKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryID(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldDeliveryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TestNotification(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldTestNotification, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawBodyHash(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldRawBodyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(paymentwebhookdelivery.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.ReceivedAt(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldReceivedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(paymentwebhookdelivery.FieldProcessedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PaymentWebhookDelivery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentwebhookdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
