// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentproviderwebhooksubscription"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentProviderWebhookSubscriptionDelete is the builder for deleting a PaymentProviderWebhookSubscription entity.
type PaymentProviderWebhookSubscriptionDelete struct {
	config
	hooks    []Hook
	mutation *PaymentProviderWebhookSubscriptionMutation
}

// Where appends a list predicates to the PaymentProviderWebhookSubscriptionDelete builder.
func (_d *PaymentProviderWebhookSubscriptionDelete) Where(ps ...predicate.PaymentProviderWebhookSubscription) *PaymentProviderWebhookSubscriptionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PaymentProviderWebhookSubscriptionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentProviderWebhookSubscriptionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PaymentProviderWebhookSubscriptionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentproviderwebhooksubscription.Table, sqlgraph.NewFieldSpec(paymentproviderwebhooksubscription.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PaymentProviderWebhookSubscriptionDeleteOne is the builder for deleting a single PaymentProviderWebhookSubscription entity.
type PaymentProviderWebhookSubscriptionDeleteOne struct {
	_d *PaymentProviderWebhookSubscriptionDelete
}

// Where appends a list predicates to the PaymentProviderWebhookSubscriptionDelete builder.
func (_d *PaymentProviderWebhookSubscriptionDeleteOne) Where(ps ...predicate.PaymentProviderWebhookSubscription) *PaymentProviderWebhookSubscriptionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PaymentProviderWebhookSubscriptionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentproviderwebhooksubscription.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentProviderWebhookSubscriptionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
