// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentproviderwebhooksubscription"
)

// PaymentProviderWebhookSubscription is the model entity for the PaymentProviderWebhookSubscription schema.
type PaymentProviderWebhookSubscription struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ProviderInstanceID holds the value of the "provider_instance_id" field.
	ProviderInstanceID int64 `json:"provider_instance_id,omitempty"`
	// ProviderKey holds the value of the "provider_key" field.
	ProviderKey string `json:"provider_key,omitempty"`
	// ExternalSubscriptionID holds the value of the "external_subscription_id" field.
	ExternalSubscriptionID string `json:"external_subscription_id,omitempty"`
	// TriggerOn holds the value of the "trigger_on" field.
	TriggerOn string `json:"trigger_on,omitempty"`
	// DeliveryVersion holds the value of the "delivery_version" field.
	DeliveryVersion string `json:"delivery_version,omitempty"`
	// DeliveryURL holds the value of the "delivery_url" field.
	DeliveryURL string `json:"delivery_url,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// SyncedAt holds the value of the "synced_at" field.
	SyncedAt *time.Time `json:"synced_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentProviderWebhookSubscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentproviderwebhooksubscription.FieldID, paymentproviderwebhooksubscription.FieldProviderInstanceID:
			values[i] = new(sql.NullInt64)
		case paymentproviderwebhooksubscription.FieldProviderKey, paymentproviderwebhooksubscription.FieldExternalSubscriptionID, paymentproviderwebhooksubscription.FieldTriggerOn, paymentproviderwebhooksubscription.FieldDeliveryVersion, paymentproviderwebhooksubscription.FieldDeliveryURL, paymentproviderwebhooksubscription.FieldStatus, paymentproviderwebhooksubscription.FieldLastError:
			values[i] = new(sql.NullString)
		case paymentproviderwebhooksubscription.FieldSyncedAt, paymentproviderwebhooksubscription.FieldCreatedAt, paymentproviderwebhooksubscription.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentProviderWebhookSubscription fields.
func (_m *PaymentProviderWebhookSubscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentproviderwebhooksubscription.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentproviderwebhooksubscription.FieldProviderInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_instance_id", values[i])
			} else if value.Valid {
				_m.ProviderInstanceID = value.Int64
			}
		case paymentproviderwebhooksubscription.FieldProviderKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_key", values[i])
			} else if value.Valid {
				_m.ProviderKey = value.String
			}
		case paymentproviderwebhooksubscription.FieldExternalSubscriptionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_subscription_id", values[i])
			} else if value.Valid {
				_m.ExternalSubscriptionID = value.String
			}
		case paymentproviderwebhooksubscription.FieldTriggerOn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_on", values[i])
			} else if value.Valid {
				_m.TriggerOn = value.String
			}
		case paymentproviderwebhooksubscription.FieldDeliveryVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delivery_version", values[i])
			} else if value.Valid {
				_m.DeliveryVersion = value.String
			}
		case paymentproviderwebhooksubscription.FieldDeliveryURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delivery_url", values[i])
			} else if value.Valid {
				_m.DeliveryURL = value.String
			}
		case paymentproviderwebhooksubscription.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paymentproviderwebhooksubscription.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case paymentproviderwebhooksubscription.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				_m.SyncedAt = new(time.Time)
				*_m.SyncedAt = value.Time
			}
		case paymentproviderwebhooksubscription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentproviderwebhooksubscription.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentProviderWebhookSubscription.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentProviderWebhookSubscription) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentProviderWebhookSubscription.
// Note that you need to call PaymentProviderWebhookSubscription.Unwrap() before calling this method if this PaymentProviderWebhookSubscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentProviderWebhookSubscription) Update() *PaymentProviderWebhookSubscriptionUpdateOne {
	return NewPaymentProviderWebhookSubscriptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentProviderWebhookSubscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentProviderWebhookSubscription) Unwrap() *PaymentProviderWebhookSubscription {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentProviderWebhookSubscription is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentProviderWebhookSubscription) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentProviderWebhookSubscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_instance_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderInstanceID))
	builder.WriteString(", ")
	builder.WriteString("provider_key=")
	builder.WriteString(_m.ProviderKey)
	builder.WriteString(", ")
	builder.WriteString("external_subscription_id=")
	builder.WriteString(_m.ExternalSubscriptionID)
	builder.WriteString(", ")
	builder.WriteString("trigger_on=")
	builder.WriteString(_m.TriggerOn)
	builder.WriteString(", ")
	builder.WriteString("delivery_version=")
	builder.WriteString(_m.DeliveryVersion)
	builder.WriteString(", ")
	builder.WriteString("delivery_url=")
	builder.WriteString(_m.DeliveryURL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SyncedAt; v != nil {
		builder.WriteString("synced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentProviderWebhookSubscriptions is a parsable slice of PaymentProviderWebhookSubscription.
type PaymentProviderWebhookSubscriptions []*PaymentProviderWebhookSubscription
