// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentwebhookdelivery"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentWebhookDeliveryDelete is the builder for deleting a PaymentWebhookDelivery entity.
type PaymentWebhookDeliveryDelete struct {
	config
	hooks    []Hook
	mutation *PaymentWebhookDeliveryMutation
}

// Where appends a list predicates to the PaymentWebhookDeliveryDelete builder.
func (_d *PaymentWebhookDeliveryDelete) Where(ps ...predicate.PaymentWebhookDelivery) *PaymentWebhookDeliveryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PaymentWebhookDeliveryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentWebhookDeliveryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PaymentWebhookDeliveryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentwebhookdelivery.Table, sqlgraph.NewFieldSpec(paymentwebhookdelivery.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PaymentWebhookDeliveryDeleteOne is the builder for deleting a single PaymentWebhookDelivery entity.
type PaymentWebhookDeliveryDeleteOne struct {
	_d *PaymentWebhookDeliveryDelete
}

// Where appends a list predicates to the PaymentWebhookDeliveryDelete builder.
func (_d *PaymentWebhookDeliveryDeleteOne) Where(ps ...predicate.PaymentWebhookDelivery) *PaymentWebhookDeliveryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PaymentWebhookDeliveryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentwebhookdelivery.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentWebhookDeliveryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
