// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentproviderwebhooksubscription"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentProviderWebhookSubscriptionUpdate is the builder for updating PaymentProviderWebhookSubscription entities.
type PaymentProviderWebhookSubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentProviderWebhookSubscriptionMutation
}

// Where appends a list predicates to the PaymentProviderWebhookSubscriptionUpdate builder.
func (_u *PaymentProviderWebhookSubscriptionUpdate) Where(ps ...predicate.PaymentProviderWebhookSubscription) *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetProviderInstanceID(v int64) *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.ResetProviderInstanceID()
	_u.mutation.SetProviderInstanceID(v)
	return _u
}

// SetNillableProviderInstanceID sets the "provider_instance_id" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetNillableProviderInstanceID(v *int64) *PaymentProviderWebhookSubscriptionUpdate {
	if v != nil {
		_u.SetProviderInstanceID(*v)
	}
	return _u
}

// AddProviderInstanceID adds value to the "provider_instance_id" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) AddProviderInstanceID(v int64) *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.AddProviderInstanceID(v)
	return _u
}

// SetProviderKey sets the "provider_key" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetProviderKey(v string) *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.SetProviderKey(v)
	return _u
}

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetNillableProviderKey(v *string) *PaymentProviderWebhookSubscriptionUpdate {
	if v != nil {
		_u.SetProviderKey(*v)
	}
	return _u
}

// SetExternalSubscriptionID sets the "external_subscription_id" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetExternalSubscriptionID(v string) *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.SetExternalSubscriptionID(v)
	return _u
}

// SetNillableExternalSubscriptionID sets the "external_subscription_id" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetNillableExternalSubscriptionID(v *string) *PaymentProviderWebhookSubscriptionUpdate {
	if v != nil {
		_u.SetExternalSubscriptionID(*v)
	}
	return _u
}

// SetTriggerOn sets the "trigger_on" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetTriggerOn(v string) *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.SetTriggerOn(v)
	return _u
}

// SetNillableTriggerOn sets the "trigger_on" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetNillableTriggerOn(v *string) *PaymentProviderWebhookSubscriptionUpdate {
	if v != nil {
		_u.SetTriggerOn(*v)
	}
	return _u
}

// SetDeliveryVersion sets the "delivery_version" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetDeliveryVersion(v string) *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.SetDeliveryVersion(v)
	return _u
}

// SetNillableDeliveryVersion sets the "delivery_version" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetNillableDeliveryVersion(v *string) *PaymentProviderWebhookSubscriptionUpdate {
	if v != nil {
		_u.SetDeliveryVersion(*v)
	}
	return _u
}

// SetDeliveryURL sets the "delivery_url" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetDeliveryURL(v string) *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.SetDeliveryURL(v)
	return _u
}

// SetNillableDeliveryURL sets the "delivery_url" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetNillableDeliveryURL(v *string) *PaymentProviderWebhookSubscriptionUpdate {
	if v != nil {
		_u.SetDeliveryURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetStatus(v string) *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetNillableStatus(v *string) *PaymentProviderWebhookSubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetLastError(v string) *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetNillableLastError(v *string) *PaymentProviderWebhookSubscriptionUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) ClearLastError() *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetSyncedAt(v time.Time) *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetNillableSyncedAt(v *time.Time) *PaymentProviderWebhookSubscriptionUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) ClearSyncedAt() *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SetUpdatedAt(v time.Time) *PaymentProviderWebhookSubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentProviderWebhookSubscriptionMutation object of the builder.
func (_u *PaymentProviderWebhookSubscriptionUpdate) Mutation() *PaymentProviderWebhookSubscriptionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentProviderWebhookSubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentProviderWebhookSubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentProviderWebhookSubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentProviderWebhookSubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentProviderWebhookSubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentproviderwebhooksubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentProviderWebhookSubscriptionUpdate) check() error {
	if v, ok := _u.mutation.ProviderKey(); ok {
		if err := paymentproviderwebhooksubscription.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.provider_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalSubscriptionID(); ok {
		if err := paymentproviderwebhooksubscription.ExternalSubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "external_subscription_id", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.external_subscription_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerOn(); ok {
		if err := paymentproviderwebhooksubscription.TriggerOnValidator(v); err != nil {
			return &ValidationError{Name: "trigger_on", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.trigger_on": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryVersion(); ok {
		if err := paymentproviderwebhooksubscription.DeliveryVersionValidator(v); err != nil {
			return &ValidationError{Name: "delivery_version", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.delivery_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryURL(); ok {
		if err := paymentproviderwebhooksubscription.DeliveryURLValidator(v); err != nil {
			return &ValidationError{Name: "delivery_url", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.delivery_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentproviderwebhooksubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentProviderWebhookSubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentproviderwebhooksubscription.Table, paymentproviderwebhooksubscription.Columns, sqlgraph.NewFieldSpec(paymentproviderwebhooksubscription.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderInstanceID(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldProviderInstanceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderInstanceID(); ok {
		_spec.AddField(paymentproviderwebhooksubscription.FieldProviderInstanceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProviderKey(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldProviderKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalSubscriptionID(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldExternalSubscriptionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerOn(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldTriggerOn, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryVersion(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldDeliveryVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryURL(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldDeliveryURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(paymentproviderwebhooksubscription.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(paymentproviderwebhooksubscription.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentproviderwebhooksubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentProviderWebhookSubscriptionUpdateOne is the builder for updating a single PaymentProviderWebhookSubscription entity.
type PaymentProviderWebhookSubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentProviderWebhookSubscriptionMutation
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetProviderInstanceID(v int64) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.ResetProviderInstanceID()
	_u.mutation.SetProviderInstanceID(v)
	return _u
}

// SetNillableProviderInstanceID sets the "provider_instance_id" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetNillableProviderInstanceID(v *int64) *PaymentProviderWebhookSubscriptionUpdateOne {
	if v != nil {
		_u.SetProviderInstanceID(*v)
	}
	return _u
}

// AddProviderInstanceID adds value to the "provider_instance_id" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) AddProviderInstanceID(v int64) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.AddProviderInstanceID(v)
	return _u
}

// SetProviderKey sets the "provider_key" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetProviderKey(v string) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.SetProviderKey(v)
	return _u
}

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetNillableProviderKey(v *string) *PaymentProviderWebhookSubscriptionUpdateOne {
	if v != nil {
		_u.SetProviderKey(*v)
	}
	return _u
}

// SetExternalSubscriptionID sets the "external_subscription_id" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetExternalSubscriptionID(v string) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.SetExternalSubscriptionID(v)
	return _u
}

// SetNillableExternalSubscriptionID sets the "external_subscription_id" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetNillableExternalSubscriptionID(v *string) *PaymentProviderWebhookSubscriptionUpdateOne {
	if v != nil {
		_u.SetExternalSubscriptionID(*v)
	}
	return _u
}

// SetTriggerOn sets the "trigger_on" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetTriggerOn(v string) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.SetTriggerOn(v)
	return _u
}

// SetNillableTriggerOn sets the "trigger_on" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetNillableTriggerOn(v *string) *PaymentProviderWebhookSubscriptionUpdateOne {
	if v != nil {
		_u.SetTriggerOn(*v)
	}
	return _u
}

// SetDeliveryVersion sets the "delivery_version" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetDeliveryVersion(v string) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.SetDeliveryVersion(v)
	return _u
}

// SetNillableDeliveryVersion sets the "delivery_version" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetNillableDeliveryVersion(v *string) *PaymentProviderWebhookSubscriptionUpdateOne {
	if v != nil {
		_u.SetDeliveryVersion(*v)
	}
	return _u
}

// SetDeliveryURL sets the "delivery_url" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetDeliveryURL(v string) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.SetDeliveryURL(v)
	return _u
}

// SetNillableDeliveryURL sets the "delivery_url" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetNillableDeliveryURL(v *string) *PaymentProviderWebhookSubscriptionUpdateOne {
	if v != nil {
		_u.SetDeliveryURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetStatus(v string) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetNillableStatus(v *string) *PaymentProviderWebhookSubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetLastError(v string) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetNillableLastError(v *string) *PaymentProviderWebhookSubscriptionUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) ClearLastError() *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetSyncedAt(v time.Time) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetNillableSyncedAt(v *time.Time) *PaymentProviderWebhookSubscriptionUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) ClearSyncedAt() *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SetUpdatedAt(v time.Time) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentProviderWebhookSubscriptionMutation object of the builder.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) Mutation() *PaymentProviderWebhookSubscriptionMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentProviderWebhookSubscriptionUpdate builder.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) Where(ps ...predicate.PaymentProviderWebhookSubscription) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) Select(field string, fields ...string) *PaymentProviderWebhookSubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentProviderWebhookSubscription entity.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) Save(ctx context.Context) (*PaymentProviderWebhookSubscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) SaveX(ctx context.Context) *PaymentProviderWebhookSubscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentproviderwebhooksubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentProviderWebhookSubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderKey(); ok {
		if err := paymentproviderwebhooksubscription.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.provider_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalSubscriptionID(); ok {
		if err := paymentproviderwebhooksubscription.ExternalSubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "external_subscription_id", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.external_subscription_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerOn(); ok {
		if err := paymentproviderwebhooksubscription.TriggerOnValidator(v); err != nil {
			return &ValidationError{Name: "trigger_on", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.trigger_on": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryVersion(); ok {
		if err := paymentproviderwebhooksubscription.DeliveryVersionValidator(v); err != nil {
			return &ValidationError{Name: "delivery_version", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.delivery_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryURL(); ok {
		if err := paymentproviderwebhooksubscription.DeliveryURLValidator(v); err != nil {
			return &ValidationError{Name: "delivery_url", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.delivery_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentproviderwebhooksubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentProviderWebhookSubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *PaymentProviderWebhookSubscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentproviderwebhooksubscription.Table, paymentproviderwebhooksubscription.Columns, sqlgraph.NewFieldSpec(paymentproviderwebhooksubscription.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentProviderWebhookSubscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentproviderwebhooksubscription.FieldID)
		for _, f := range fields {
			if !paymentproviderwebhooksubscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentproviderwebhooksubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderInstanceID(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldProviderInstanceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderInstanceID(); ok {
		_spec.AddField(paymentproviderwebhooksubscription.FieldProviderInstanceID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProviderKey(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldProviderKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalSubscriptionID(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldExternalSubscriptionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerOn(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldTriggerOn, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryVersion(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldDeliveryVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeliveryURL(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldDeliveryURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(paymentproviderwebhooksubscription.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(paymentproviderwebhooksubscription.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PaymentProviderWebhookSubscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentproviderwebhooksubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
