// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentproviderwebhooksubscription"
)

// PaymentProviderWebhookSubscriptionCreate is the builder for creating a PaymentProviderWebhookSubscription entity.
type PaymentProviderWebhookSubscriptionCreate struct {
	config
	mutation *PaymentProviderWebhookSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetProviderInstanceID(v int64) *PaymentProviderWebhookSubscriptionCreate {
	_c.mutation.SetProviderInstanceID(v)
	return _c
}

// SetProviderKey sets the "provider_key" field.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetProviderKey(v string) *PaymentProviderWebhookSubscriptionCreate {
	_c.mutation.SetProviderKey(v)
	return _c
}

// SetExternalSubscriptionID sets the "external_subscription_id" field.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetExternalSubscriptionID(v string) *PaymentProviderWebhookSubscriptionCreate {
	_c.mutation.SetExternalSubscriptionID(v)
	return _c
}

// SetNillableExternalSubscriptionID sets the "external_subscription_id" field if the given value is not nil.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetNillableExternalSubscriptionID(v *string) *PaymentProviderWebhookSubscriptionCreate {
	if v != nil {
		_c.SetExternalSubscriptionID(*v)
	}
	return _c
}

// SetTriggerOn sets the "trigger_on" field.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetTriggerOn(v string) *PaymentProviderWebhookSubscriptionCreate {
	_c.mutation.SetTriggerOn(v)
	return _c
}

// SetDeliveryVersion sets the "delivery_version" field.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetDeliveryVersion(v string) *PaymentProviderWebhookSubscriptionCreate {
	_c.mutation.SetDeliveryVersion(v)
	return _c
}

// SetDeliveryURL sets the "delivery_url" field.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetDeliveryURL(v string) *PaymentProviderWebhookSubscriptionCreate {
	_c.mutation.SetDeliveryURL(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetStatus(v string) *PaymentProviderWebhookSubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetNillableStatus(v *string) *PaymentProviderWebhookSubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetLastError(v string) *PaymentProviderWebhookSubscriptionCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetNillableLastError(v *string) *PaymentProviderWebhookSubscriptionCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetSyncedAt(v time.Time) *PaymentProviderWebhookSubscriptionCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetNillableSyncedAt(v *time.Time) *PaymentProviderWebhookSubscriptionCreate {
	if v != nil {
		_c.SetSyncedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetCreatedAt(v time.Time) *PaymentProviderWebhookSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *PaymentProviderWebhookSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetUpdatedAt(v time.Time) *PaymentProviderWebhookSubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentProviderWebhookSubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *PaymentProviderWebhookSubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PaymentProviderWebhookSubscriptionMutation object of the builder.
func (_c *PaymentProviderWebhookSubscriptionCreate) Mutation() *PaymentProviderWebhookSubscriptionMutation {
	return _c.mutation
}

// Save creates the PaymentProviderWebhookSubscription in the database.
func (_c *PaymentProviderWebhookSubscriptionCreate) Save(ctx context.Context) (*PaymentProviderWebhookSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentProviderWebhookSubscriptionCreate) SaveX(ctx context.Context) *PaymentProviderWebhookSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentProviderWebhookSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentProviderWebhookSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentProviderWebhookSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.ExternalSubscriptionID(); !ok {
		v := paymentproviderwebhooksubscription.DefaultExternalSubscriptionID
		_c.mutation.SetExternalSubscriptionID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentproviderwebhooksubscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentproviderwebhooksubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentproviderwebhooksubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentProviderWebhookSubscriptionCreate) check() error {
	if _, ok := _c.mutation.ProviderInstanceID(); !ok {
		return &ValidationError{Name: "provider_instance_id", err: errors.New(`ent: missing required field "PaymentProviderWebhookSubscription.provider_instance_id"`)}
	}
	if _, ok := _c.mutation.ProviderKey(); !ok {
		return &ValidationError{Name: "provider_key", err: errors.New(`ent: missing required field "PaymentProviderWebhookSubscription.provider_key"`)}
	}
	if v, ok := _c.mutation.ProviderKey(); ok {
		if err := paymentproviderwebhooksubscription.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.provider_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExternalSubscriptionID(); !ok {
		return &ValidationError{Name: "external_subscription_id", err: errors.New(`ent: missing required field "PaymentProviderWebhookSubscription.external_subscription_id"`)}
	}
	if v, ok := _c.mutation.ExternalSubscriptionID(); ok {
		if err := paymentproviderwebhooksubscription.ExternalSubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "external_subscription_id", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.external_subscription_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TriggerOn(); !ok {
		return &ValidationError{Name: "trigger_on", err: errors.New(`ent: missing required field "PaymentProviderWebhookSubscription.trigger_on"`)}
	}
	if v, ok := _c.mutation.TriggerOn(); ok {
		if err := paymentproviderwebhooksubscription.TriggerOnValidator(v); err != nil {
			return &ValidationError{Name: "trigger_on", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.trigger_on": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeliveryVersion(); !ok {
		return &ValidationError{Name: "delivery_version", err: errors.New(`ent: missing required field "PaymentProviderWebhookSubscription.delivery_version"`)}
	}
	if v, ok := _c.mutation.DeliveryVersion(); ok {
		if err := paymentproviderwebhooksubscription.DeliveryVersionValidator(v); err != nil {
			return &ValidationError{Name: "delivery_version", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.delivery_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeliveryURL(); !ok {
		return &ValidationError{Name: "delivery_url", err: errors.New(`ent: missing required field "PaymentProviderWebhookSubscription.delivery_url"`)}
	}
	if v, ok := _c.mutation.DeliveryURL(); ok {
		if err := paymentproviderwebhooksubscription.DeliveryURLValidator(v); err != nil {
			return &ValidationError{Name: "delivery_url", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.delivery_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentProviderWebhookSubscription.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentproviderwebhooksubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentProviderWebhookSubscription.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentProviderWebhookSubscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentProviderWebhookSubscription.updated_at"`)}
	}
	return nil
}

func (_c *PaymentProviderWebhookSubscriptionCreate) sqlSave(ctx context.Context) (*PaymentProviderWebhookSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentProviderWebhookSubscriptionCreate) createSpec() (*PaymentProviderWebhookSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentProviderWebhookSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentproviderwebhooksubscription.Table, sqlgraph.NewFieldSpec(paymentproviderwebhooksubscription.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ProviderInstanceID(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldProviderInstanceID, field.TypeInt64, value)
		_node.ProviderInstanceID = value
	}
	if value, ok := _c.mutation.ProviderKey(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldProviderKey, field.TypeString, value)
		_node.ProviderKey = value
	}
	if value, ok := _c.mutation.ExternalSubscriptionID(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldExternalSubscriptionID, field.TypeString, value)
		_node.ExternalSubscriptionID = value
	}
	if value, ok := _c.mutation.TriggerOn(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldTriggerOn, field.TypeString, value)
		_node.TriggerOn = value
	}
	if value, ok := _c.mutation.DeliveryVersion(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldDeliveryVersion, field.TypeString, value)
		_node.DeliveryVersion = value
	}
	if value, ok := _c.mutation.DeliveryURL(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldDeliveryURL, field.TypeString, value)
		_node.DeliveryURL = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentproviderwebhooksubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentProviderWebhookSubscription.Create().
//		SetProviderInstanceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentProviderWebhookSubscriptionUpsert) {
//			SetProviderInstanceID(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentProviderWebhookSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *PaymentProviderWebhookSubscriptionUpsertOne {
	_c.conflict = opts
	return &PaymentProviderWebhookSubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentProviderWebhookSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentProviderWebhookSubscriptionCreate) OnConflictColumns(columns ...string) *PaymentProviderWebhookSubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentProviderWebhookSubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// PaymentProviderWebhookSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one PaymentProviderWebhookSubscription node.
	PaymentProviderWebhookSubscriptionUpsertOne struct {
		create *PaymentProviderWebhookSubscriptionCreate
	}

	// PaymentProviderWebhookSubscriptionUpsert is the "OnConflict" setter.
	PaymentProviderWebhookSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) SetProviderInstanceID(v int64) *PaymentProviderWebhookSubscriptionUpsert {
	u.Set(paymentproviderwebhooksubscription.FieldProviderInstanceID, v)
	return u
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsert) UpdateProviderInstanceID() *PaymentProviderWebhookSubscriptionUpsert {
	u.SetExcluded(paymentproviderwebhooksubscription.FieldProviderInstanceID)
	return u
}

// AddProviderInstanceID adds v to the "provider_instance_id" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) AddProviderInstanceID(v int64) *PaymentProviderWebhookSubscriptionUpsert {
	u.Add(paymentproviderwebhooksubscription.FieldProviderInstanceID, v)
	return u
}

// SetProviderKey sets the "provider_key" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) SetProviderKey(v string) *PaymentProviderWebhookSubscriptionUpsert {
	u.Set(paymentproviderwebhooksubscription.FieldProviderKey, v)
	return u
}

// UpdateProviderKey sets the "provider_key" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsert) UpdateProviderKey() *PaymentProviderWebhookSubscriptionUpsert {
	u.SetExcluded(paymentproviderwebhooksubscription.FieldProviderKey)
	return u
}

// SetExternalSubscriptionID sets the "external_subscription_id" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) SetExternalSubscriptionID(v string) *PaymentProviderWebhookSubscriptionUpsert {
	u.Set(paymentproviderwebhooksubscription.FieldExternalSubscriptionID, v)
	return u
}

// UpdateExternalSubscriptionID sets the "external_subscription_id" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsert) UpdateExternalSubscriptionID() *PaymentProviderWebhookSubscriptionUpsert {
	u.SetExcluded(paymentproviderwebhooksubscription.FieldExternalSubscriptionID)
	return u
}

// SetTriggerOn sets the "trigger_on" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) SetTriggerOn(v string) *PaymentProviderWebhookSubscriptionUpsert {
	u.Set(paymentproviderwebhooksubscription.FieldTriggerOn, v)
	return u
}

// UpdateTriggerOn sets the "trigger_on" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsert) UpdateTriggerOn() *PaymentProviderWebhookSubscriptionUpsert {
	u.SetExcluded(paymentproviderwebhooksubscription.FieldTriggerOn)
	return u
}

// SetDeliveryVersion sets the "delivery_version" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) SetDeliveryVersion(v string) *PaymentProviderWebhookSubscriptionUpsert {
	u.Set(paymentproviderwebhooksubscription.FieldDeliveryVersion, v)
	return u
}

// UpdateDeliveryVersion sets the "delivery_version" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsert) UpdateDeliveryVersion() *PaymentProviderWebhookSubscriptionUpsert {
	u.SetExcluded(paymentproviderwebhooksubscription.FieldDeliveryVersion)
	return u
}

// SetDeliveryURL sets the "delivery_url" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) SetDeliveryURL(v string) *PaymentProviderWebhookSubscriptionUpsert {
	u.Set(paymentproviderwebhooksubscription.FieldDeliveryURL, v)
	return u
}

// UpdateDeliveryURL sets the "delivery_url" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsert) UpdateDeliveryURL() *PaymentProviderWebhookSubscriptionUpsert {
	u.SetExcluded(paymentproviderwebhooksubscription.FieldDeliveryURL)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) SetStatus(v string) *PaymentProviderWebhookSubscriptionUpsert {
	u.Set(paymentproviderwebhooksubscription.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsert) UpdateStatus() *PaymentProviderWebhookSubscriptionUpsert {
	u.SetExcluded(paymentproviderwebhooksubscription.FieldStatus)
	return u
}

// SetLastError sets the "last_error" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) SetLastError(v string) *PaymentProviderWebhookSubscriptionUpsert {
	u.Set(paymentproviderwebhooksubscription.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsert) UpdateLastError() *PaymentProviderWebhookSubscriptionUpsert {
	u.SetExcluded(paymentproviderwebhooksubscription.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) ClearLastError() *PaymentProviderWebhookSubscriptionUpsert {
	u.SetNull(paymentproviderwebhooksubscription.FieldLastError)
	return u
}

// SetSyncedAt sets the "synced_at" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) SetSyncedAt(v time.Time) *PaymentProviderWebhookSubscriptionUpsert {
	u.Set(paymentproviderwebhooksubscription.FieldSyncedAt, v)
	return u
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsert) UpdateSyncedAt() *PaymentProviderWebhookSubscriptionUpsert {
	u.SetExcluded(paymentproviderwebhooksubscription.FieldSyncedAt)
	return u
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) ClearSyncedAt() *PaymentProviderWebhookSubscriptionUpsert {
	u.SetNull(paymentproviderwebhooksubscription.FieldSyncedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentProviderWebhookSubscriptionUpsert) SetUpdatedAt(v time.Time) *PaymentProviderWebhookSubscriptionUpsert {
	u.Set(paymentproviderwebhooksubscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsert) UpdateUpdatedAt() *PaymentProviderWebhookSubscriptionUpsert {
	u.SetExcluded(paymentproviderwebhooksubscription.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentProviderWebhookSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentProviderWebhookSubscriptionUpsertOne) UpdateNewValues() *PaymentProviderWebhookSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentproviderwebhooksubscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentProviderWebhookSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentProviderWebhookSubscriptionUpsertOne) Ignore() *PaymentProviderWebhookSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) DoNothing() *PaymentProviderWebhookSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentProviderWebhookSubscriptionCreate.OnConflict
// documentation for more info.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) Update(set func(*PaymentProviderWebhookSubscriptionUpsert)) *PaymentProviderWebhookSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentProviderWebhookSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) SetProviderInstanceID(v int64) *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetProviderInstanceID(v)
	})
}

// AddProviderInstanceID adds v to the "provider_instance_id" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) AddProviderInstanceID(v int64) *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.AddProviderInstanceID(v)
	})
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) UpdateProviderInstanceID() *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateProviderInstanceID()
	})
}

// SetProviderKey sets the "provider_key" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) SetProviderKey(v string) *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetProviderKey(v)
	})
}

// UpdateProviderKey sets the "provider_key" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) UpdateProviderKey() *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateProviderKey()
	})
}

// SetExternalSubscriptionID sets the "external_subscription_id" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) SetExternalSubscriptionID(v string) *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetExternalSubscriptionID(v)
	})
}

// UpdateExternalSubscriptionID sets the "external_subscription_id" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) UpdateExternalSubscriptionID() *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateExternalSubscriptionID()
	})
}

// SetTriggerOn sets the "trigger_on" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) SetTriggerOn(v string) *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetTriggerOn(v)
	})
}

// UpdateTriggerOn sets the "trigger_on" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) UpdateTriggerOn() *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateTriggerOn()
	})
}

// SetDeliveryVersion sets the "delivery_version" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) SetDeliveryVersion(v string) *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetDeliveryVersion(v)
	})
}

// UpdateDeliveryVersion sets the "delivery_version" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) UpdateDeliveryVersion() *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateDeliveryVersion()
	})
}

// SetDeliveryURL sets the "delivery_url" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) SetDeliveryURL(v string) *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetDeliveryURL(v)
	})
}

// UpdateDeliveryURL sets the "delivery_url" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) UpdateDeliveryURL() *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateDeliveryURL()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) SetStatus(v string) *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) UpdateStatus() *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetLastError sets the "last_error" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) SetLastError(v string) *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) UpdateLastError() *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) ClearLastError() *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.ClearLastError()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) SetSyncedAt(v time.Time) *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) UpdateSyncedAt() *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateSyncedAt()
	})
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) ClearSyncedAt() *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.ClearSyncedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) SetUpdatedAt(v time.Time) *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) UpdateUpdatedAt() *PaymentProviderWebhookSubscriptionUpsertOne {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentProviderWebhookSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentProviderWebhookSubscriptionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentProviderWebhookSubscriptionCreateBulk is the builder for creating many PaymentProviderWebhookSubscription entities in bulk.
type PaymentProviderWebhookSubscriptionCreateBulk struct {
	config
	err      error
	builders []*PaymentProviderWebhookSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentProviderWebhookSubscription entities in the database.
func (_c *PaymentProviderWebhookSubscriptionCreateBulk) Save(ctx context.Context) ([]*PaymentProviderWebhookSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentProviderWebhookSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentProviderWebhookSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentProviderWebhookSubscriptionCreateBulk) SaveX(ctx context.Context) []*PaymentProviderWebhookSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentProviderWebhookSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentProviderWebhookSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentProviderWebhookSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentProviderWebhookSubscriptionUpsert) {
//			SetProviderInstanceID(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentProviderWebhookSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentProviderWebhookSubscriptionUpsertBulk {
	_c.conflict = opts
	return &PaymentProviderWebhookSubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentProviderWebhookSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentProviderWebhookSubscriptionCreateBulk) OnConflictColumns(columns ...string) *PaymentProviderWebhookSubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentProviderWebhookSubscriptionUpsertBulk{
		create: _c,
	}
}

// PaymentProviderWebhookSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentProviderWebhookSubscription nodes.
type PaymentProviderWebhookSubscriptionUpsertBulk struct {
	create *PaymentProviderWebhookSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentProviderWebhookSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) UpdateNewValues() *PaymentProviderWebhookSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentproviderwebhooksubscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentProviderWebhookSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) Ignore() *PaymentProviderWebhookSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) DoNothing() *PaymentProviderWebhookSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentProviderWebhookSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) Update(set func(*PaymentProviderWebhookSubscriptionUpsert)) *PaymentProviderWebhookSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentProviderWebhookSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) SetProviderInstanceID(v int64) *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetProviderInstanceID(v)
	})
}

// AddProviderInstanceID adds v to the "provider_instance_id" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) AddProviderInstanceID(v int64) *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.AddProviderInstanceID(v)
	})
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) UpdateProviderInstanceID() *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateProviderInstanceID()
	})
}

// SetProviderKey sets the "provider_key" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) SetProviderKey(v string) *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetProviderKey(v)
	})
}

// UpdateProviderKey sets the "provider_key" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) UpdateProviderKey() *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateProviderKey()
	})
}

// SetExternalSubscriptionID sets the "external_subscription_id" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) SetExternalSubscriptionID(v string) *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetExternalSubscriptionID(v)
	})
}

// UpdateExternalSubscriptionID sets the "external_subscription_id" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) UpdateExternalSubscriptionID() *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateExternalSubscriptionID()
	})
}

// SetTriggerOn sets the "trigger_on" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) SetTriggerOn(v string) *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetTriggerOn(v)
	})
}

// UpdateTriggerOn sets the "trigger_on" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) UpdateTriggerOn() *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateTriggerOn()
	})
}

// SetDeliveryVersion sets the "delivery_version" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) SetDeliveryVersion(v string) *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetDeliveryVersion(v)
	})
}

// UpdateDeliveryVersion sets the "delivery_version" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) UpdateDeliveryVersion() *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateDeliveryVersion()
	})
}

// SetDeliveryURL sets the "delivery_url" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) SetDeliveryURL(v string) *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetDeliveryURL(v)
	})
}

// UpdateDeliveryURL sets the "delivery_url" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) UpdateDeliveryURL() *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateDeliveryURL()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) SetStatus(v string) *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) UpdateStatus() *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetLastError sets the "last_error" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) SetLastError(v string) *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) UpdateLastError() *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) ClearLastError() *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.ClearLastError()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) SetSyncedAt(v time.Time) *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) UpdateSyncedAt() *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateSyncedAt()
	})
}

// ClearSyncedAt clears the value of the "synced_at" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) ClearSyncedAt() *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.ClearSyncedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) UpdateUpdatedAt() *PaymentProviderWebhookSubscriptionUpsertBulk {
	return u.Update(func(s *PaymentProviderWebhookSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentProviderWebhookSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentProviderWebhookSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentProviderWebhookSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
