// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentwebhookdelivery"
)

// PaymentWebhookDelivery is the model entity for the PaymentWebhookDelivery schema.
type PaymentWebhookDelivery struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ProviderKey holds the value of the "provider_key" field.
	ProviderKey string `json:"provider_key,omitempty"`
	// DeliveryID holds the value of the "delivery_id" field.
	DeliveryID string `json:"delivery_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// TestNotification holds the value of the "test_notification" field.
	TestNotification bool `json:"test_notification,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RawBodyHash holds the value of the "raw_body_hash" field.
	RawBodyHash string `json:"raw_body_hash,omitempty"`
	// Error holds the value of the "error" field.
	Error *string `json:"error,omitempty"`
	// ReceivedAt holds the value of the "received_at" field.
	ReceivedAt time.Time `json:"received_at,omitempty"`
	// ProcessedAt holds the value of the "processed_at" field.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentWebhookDelivery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentwebhookdelivery.FieldTestNotification:
			values[i] = new(sql.NullBool)
		case paymentwebhookdelivery.FieldID:
			values[i] = new(sql.NullInt64)
		case paymentwebhookdelivery.FieldProviderKey, paymentwebhookdelivery.FieldDeliveryID, paymentwebhookdelivery.FieldEventType, paymentwebhookdelivery.FieldStatus, paymentwebhookdelivery.FieldRawBodyHash, paymentwebhookdelivery.FieldError:
			values[i] = new(sql.NullString)
		case paymentwebhookdelivery.FieldReceivedAt, paymentwebhookdelivery.FieldProcessedAt, paymentwebhookdelivery.FieldCreatedAt, paymentwebhookdelivery.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentWebhookDelivery fields.
func (_m *PaymentWebhookDelivery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentwebhookdelivery.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentwebhookdelivery.FieldProviderKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_key", values[i])
			} else if value.Valid {
				_m.ProviderKey = value.String
			}
		case paymentwebhookdelivery.FieldDeliveryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delivery_id", values[i])
			} else if value.Valid {
				_m.DeliveryID = value.String
			}
		case paymentwebhookdelivery.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case paymentwebhookdelivery.FieldTestNotification:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field test_notification", values[i])
			} else if value.Valid {
				_m.TestNotification = value.Bool
			}
		case paymentwebhookdelivery.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paymentwebhookdelivery.FieldRawBodyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_body_hash", values[i])
			} else if value.Valid {
				_m.RawBodyHash = value.String
			}
		case paymentwebhookdelivery.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = new(string)
				*_m.Error = value.String
			}
		case paymentwebhookdelivery.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = value.Time
			}
		case paymentwebhookdelivery.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				_m.ProcessedAt = new(time.Time)
				*_m.ProcessedAt = value.Time
			}
		case paymentwebhookdelivery.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentwebhookdelivery.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentWebhookDelivery.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentWebhookDelivery) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentWebhookDelivery.
// Note that you need to call PaymentWebhookDelivery.Unwrap() before calling this method if this PaymentWebhookDelivery
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentWebhookDelivery) Update() *PaymentWebhookDeliveryUpdateOne {
	return NewPaymentWebhookDeliveryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentWebhookDelivery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentWebhookDelivery) Unwrap() *PaymentWebhookDelivery {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentWebhookDelivery is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentWebhookDelivery) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentWebhookDelivery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_key=")
	builder.WriteString(_m.ProviderKey)
	builder.WriteString(", ")
	builder.WriteString("delivery_id=")
	builder.WriteString(_m.DeliveryID)
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("test_notification=")
	builder.WriteString(fmt.Sprintf("%v", _m.TestNotification))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("raw_body_hash=")
	builder.WriteString(_m.RawBodyHash)
	builder.WriteString(", ")
	if v := _m.Error; v != nil {
		builder.WriteString("error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(_m.ReceivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentWebhookDeliveries is a parsable slice of PaymentWebhookDelivery.
type PaymentWebhookDeliveries []*PaymentWebhookDelivery
