// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentwebhookdelivery"
)

// PaymentWebhookDeliveryCreate is the builder for creating a PaymentWebhookDelivery entity.
type PaymentWebhookDeliveryCreate struct {
	config
	mutation *PaymentWebhookDeliveryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProviderKey sets the "provider_key" field.
func (_c *PaymentWebhookDeliveryCreate) SetProviderKey(v string) *PaymentWebhookDeliveryCreate {
	_c.mutation.SetProviderKey(v)
	return _c
}

// SetDeliveryID sets the "delivery_id" field.
func (_c *PaymentWebhookDeliveryCreate) SetDeliveryID(v string) *PaymentWebhookDeliveryCreate {
	_c.mutation.SetDeliveryID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *PaymentWebhookDeliveryCreate) SetEventType(v string) *PaymentWebhookDeliveryCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_c *PaymentWebhookDeliveryCreate) SetNillableEventType(v *string) *PaymentWebhookDeliveryCreate {
	if v != nil {
		_c.SetEventType(*v)
	}
	return _c
}

// SetTestNotification sets the "test_notification" field.
func (_c *PaymentWebhookDeliveryCreate) SetTestNotification(v bool) *PaymentWebhookDeliveryCreate {
	_c.mutation.SetTestNotification(v)
	return _c
}

// SetNillableTestNotification sets the "test_notification" field if the given value is not nil.
func (_c *PaymentWebhookDeliveryCreate) SetNillableTestNotification(v *bool) *PaymentWebhookDeliveryCreate {
	if v != nil {
		_c.SetTestNotification(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentWebhookDeliveryCreate) SetStatus(v string) *PaymentWebhookDeliveryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentWebhookDeliveryCreate) SetNillableStatus(v *string) *PaymentWebhookDeliveryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRawBodyHash sets the "raw_body_hash" field.
func (_c *PaymentWebhookDeliveryCreate) SetRawBodyHash(v string) *PaymentWebhookDeliveryCreate {
	_c.mutation.SetRawBodyHash(v)
	return _c
}

// SetNillableRawBodyHash sets the "raw_body_hash" field if the given value is not nil.
func (_c *PaymentWebhookDeliveryCreate) SetNillableRawBodyHash(v *string) *PaymentWebhookDeliveryCreate {
	if v != nil {
		_c.SetRawBodyHash(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *PaymentWebhookDeliveryCreate) SetError(v string) *PaymentWebhookDeliveryCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *PaymentWebhookDeliveryCreate) SetNillableError(v *string) *PaymentWebhookDeliveryCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetReceivedAt sets the "received_at" field.
func (_c *PaymentWebhookDeliveryCreate) SetReceivedAt(v time.Time) *PaymentWebhookDeliveryCreate {
	_c.mutation.SetReceivedAt(v)
	return _c
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_c *PaymentWebhookDeliveryCreate) SetNillableReceivedAt(v *time.Time) *PaymentWebhookDeliveryCreate {
	if v != nil {
		_c.SetReceivedAt(*v)
	}
	return _c
}

// SetProcessedAt sets the "processed_at" field.
func (_c *PaymentWebhookDeliveryCreate) SetProcessedAt(v time.Time) *PaymentWebhookDeliveryCreate {
	_c.mutation.SetProcessedAt(v)
	return _c
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_c *PaymentWebhookDeliveryCreate) SetNillableProcessedAt(v *time.Time) *PaymentWebhookDeliveryCreate {
	if v != nil {
		_c.SetProcessedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentWebhookDeliveryCreate) SetCreatedAt(v time.Time) *PaymentWebhookDeliveryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentWebhookDeliveryCreate) SetNillableCreatedAt(v *time.Time) *PaymentWebhookDeliveryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentWebhookDeliveryCreate) SetUpdatedAt(v time.Time) *PaymentWebhookDeliveryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentWebhookDeliveryCreate) SetNillableUpdatedAt(v *time.Time) *PaymentWebhookDeliveryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PaymentWebhookDeliveryMutation object of the builder.
func (_c *PaymentWebhookDeliveryCreate) Mutation() *PaymentWebhookDeliveryMutation {
	return _c.mutation
}

// Save creates the PaymentWebhookDelivery in the database.
func (_c *PaymentWebhookDeliveryCreate) Save(ctx context.Context) (*PaymentWebhookDelivery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentWebhookDeliveryCreate) SaveX(ctx context.Context) *PaymentWebhookDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentWebhookDeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentWebhookDeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentWebhookDeliveryCreate) defaults() {
	if _, ok := _c.mutation.EventType(); !ok {
		v := paymentwebhookdelivery.DefaultEventType
		_c.mutation.SetEventType(v)
	}
	if _, ok := _c.mutation.TestNotification(); !ok {
		v := paymentwebhookdelivery.DefaultTestNotification
		_c.mutation.SetTestNotification(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentwebhookdelivery.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RawBodyHash(); !ok {
		v := paymentwebhookdelivery.DefaultRawBodyHash
		_c.mutation.SetRawBodyHash(v)
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		v := paymentwebhookdelivery.DefaultReceivedAt()
		_c.mutation.SetReceivedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentwebhookdelivery.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentwebhookdelivery.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentWebhookDeliveryCreate) check() error {
	if _, ok := _c.mutation.ProviderKey(); !ok {
		return &ValidationError{Name: "provider_key", err: errors.New(`ent: missing required field "PaymentWebhookDelivery.provider_key"`)}
	}
	if v, ok := _c.mutation.ProviderKey(); ok {
		if err := paymentwebhookdelivery.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.provider_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeliveryID(); !ok {
		return &ValidationError{Name: "delivery_id", err: errors.New(`ent: missing required field "PaymentWebhookDelivery.delivery_id"`)}
	}
	if v, ok := _c.mutation.DeliveryID(); ok {
		if err := paymentwebhookdelivery.DeliveryIDValidator(v); err != nil {
			return &ValidationError{Name: "delivery_id", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.delivery_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "PaymentWebhookDelivery.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := paymentwebhookdelivery.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TestNotification(); !ok {
		return &ValidationError{Name: "test_notification", err: errors.New(`ent: missing required field "PaymentWebhookDelivery.test_notification"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentWebhookDelivery.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentwebhookdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RawBodyHash(); !ok {
		return &ValidationError{Name: "raw_body_hash", err: errors.New(`ent: missing required field "PaymentWebhookDelivery.raw_body_hash"`)}
	}
	if v, ok := _c.mutation.RawBodyHash(); ok {
		if err := paymentwebhookdelivery.RawBodyHashValidator(v); err != nil {
			return &ValidationError{Name: "raw_body_hash", err: fmt.Errorf(`ent: validator failed for field "PaymentWebhookDelivery.raw_body_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "received_at", err: errors.New(`ent: missing required field "PaymentWebhookDelivery.received_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentWebhookDelivery.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentWebhookDelivery.updated_at"`)}
	}
	return nil
}

func (_c *PaymentWebhookDeliveryCreate) sqlSave(ctx context.Context) (*PaymentWebhookDelivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentWebhookDeliveryCreate) createSpec() (*PaymentWebhookDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentWebhookDelivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentwebhookdelivery.Table, sqlgraph.NewFieldSpec(paymentwebhookdelivery.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ProviderKey(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldProviderKey, field.TypeString, value)
		_node.ProviderKey = value
	}
	if value, ok := _c.mutation.DeliveryID(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldDeliveryID, field.TypeString, value)
		_node.DeliveryID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.TestNotification(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldTestNotification, field.TypeBool, value)
		_node.TestNotification = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RawBodyHash(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldRawBodyHash, field.TypeString, value)
		_node.RawBodyHash = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	if value, ok := _c.mutation.ReceivedAt(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = value
	}
	if value, ok := _c.mutation.ProcessedAt(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentwebhookdelivery.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentWebhookDelivery.Create().
//		SetProviderKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentWebhookDeliveryUpsert) {
//			SetProviderKey(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentWebhookDeliveryCreate) OnConflict(opts ...sql.ConflictOption) *PaymentWebhookDeliveryUpsertOne {
	_c.conflict = opts
	return &PaymentWebhookDeliveryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentWebhookDelivery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentWebhookDeliveryCreate) OnConflictColumns(columns ...string) *PaymentWebhookDeliveryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentWebhookDeliveryUpsertOne{
		create: _c,
	}
}

type (
	// PaymentWebhookDeliveryUpsertOne is the builder for "upsert"-ing
	//  one PaymentWebhookDelivery node.
	PaymentWebhookDeliveryUpsertOne struct {
		create *PaymentWebhookDeliveryCreate
	}

	// PaymentWebhookDeliveryUpsert is the "OnConflict" setter.
	PaymentWebhookDeliveryUpsert struct {
		*sql.UpdateSet
	}
)

// SetProviderKey sets the "provider_key" field.
func (u *PaymentWebhookDeliveryUpsert) SetProviderKey(v string) *PaymentWebhookDeliveryUpsert {
	u.Set(paymentwebhookdelivery.FieldProviderKey, v)
	return u
}

// UpdateProviderKey sets the "provider_key" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsert) UpdateProviderKey() *PaymentWebhookDeliveryUpsert {
	u.SetExcluded(paymentwebhookdelivery.FieldProviderKey)
	return u
}

// SetDeliveryID sets the "delivery_id" field.
func (u *PaymentWebhookDeliveryUpsert) SetDeliveryID(v string) *PaymentWebhookDeliveryUpsert {
	u.Set(paymentwebhookdelivery.FieldDeliveryID, v)
	return u
}

// UpdateDeliveryID sets the "delivery_id" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsert) UpdateDeliveryID() *PaymentWebhookDeliveryUpsert {
	u.SetExcluded(paymentwebhookdelivery.FieldDeliveryID)
	return u
}

// SetEventType sets the "event_type" field.
func (u *PaymentWebhookDeliveryUpsert) SetEventType(v string) *PaymentWebhookDeliveryUpsert {
	u.Set(paymentwebhookdelivery.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsert) UpdateEventType() *PaymentWebhookDeliveryUpsert {
	u.SetExcluded(paymentwebhookdelivery.FieldEventType)
	return u
}

// SetTestNotification sets the "test_notification" field.
func (u *PaymentWebhookDeliveryUpsert) SetTestNotification(v bool) *PaymentWebhookDeliveryUpsert {
	u.Set(paymentwebhookdelivery.FieldTestNotification, v)
	return u
}

// UpdateTestNotification sets the "test_notification" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsert) UpdateTestNotification() *PaymentWebhookDeliveryUpsert {
	u.SetExcluded(paymentwebhookdelivery.FieldTestNotification)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentWebhookDeliveryUpsert) SetStatus(v string) *PaymentWebhookDeliveryUpsert {
	u.Set(paymentwebhookdelivery.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsert) UpdateStatus() *PaymentWebhookDeliveryUpsert {
	u.SetExcluded(paymentwebhookdelivery.FieldStatus)
	return u
}

// SetRawBodyHash sets the "raw_body_hash" field.
func (u *PaymentWebhookDeliveryUpsert) SetRawBodyHash(v string) *PaymentWebhookDeliveryUpsert {
	u.Set(paymentwebhookdelivery.FieldRawBodyHash, v)
	return u
}

// UpdateRawBodyHash sets the "raw_body_hash" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsert) UpdateRawBodyHash() *PaymentWebhookDeliveryUpsert {
	u.SetExcluded(paymentwebhookdelivery.FieldRawBodyHash)
	return u
}

// SetError sets the "error" field.
func (u *PaymentWebhookDeliveryUpsert) SetError(v string) *PaymentWebhookDeliveryUpsert {
	u.Set(paymentwebhookdelivery.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsert) UpdateError() *PaymentWebhookDeliveryUpsert {
	u.SetExcluded(paymentwebhookdelivery.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *PaymentWebhookDeliveryUpsert) ClearError() *PaymentWebhookDeliveryUpsert {
	u.SetNull(paymentwebhookdelivery.FieldError)
	return u
}

// SetReceivedAt sets the "received_at" field.
func (u *PaymentWebhookDeliveryUpsert) SetReceivedAt(v time.Time) *PaymentWebhookDeliveryUpsert {
	u.Set(paymentwebhookdelivery.FieldReceivedAt, v)
	return u
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsert) UpdateReceivedAt() *PaymentWebhookDeliveryUpsert {
	u.SetExcluded(paymentwebhookdelivery.FieldReceivedAt)
	return u
}

// SetProcessedAt sets the "processed_at" field.
func (u *PaymentWebhookDeliveryUpsert) SetProcessedAt(v time.Time) *PaymentWebhookDeliveryUpsert {
	u.Set(paymentwebhookdelivery.FieldProcessedAt, v)
	return u
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsert) UpdateProcessedAt() *PaymentWebhookDeliveryUpsert {
	u.SetExcluded(paymentwebhookdelivery.FieldProcessedAt)
	return u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *PaymentWebhookDeliveryUpsert) ClearProcessedAt() *PaymentWebhookDeliveryUpsert {
	u.SetNull(paymentwebhookdelivery.FieldProcessedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentWebhookDeliveryUpsert) SetUpdatedAt(v time.Time) *PaymentWebhookDeliveryUpsert {
	u.Set(paymentwebhookdelivery.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsert) UpdateUpdatedAt() *PaymentWebhookDeliveryUpsert {
	u.SetExcluded(paymentwebhookdelivery.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentWebhookDelivery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentWebhookDeliveryUpsertOne) UpdateNewValues() *PaymentWebhookDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentwebhookdelivery.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentWebhookDelivery.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentWebhookDeliveryUpsertOne) Ignore() *PaymentWebhookDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentWebhookDeliveryUpsertOne) DoNothing() *PaymentWebhookDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentWebhookDeliveryCreate.OnConflict
// documentation for more info.
func (u *PaymentWebhookDeliveryUpsertOne) Update(set func(*PaymentWebhookDeliveryUpsert)) *PaymentWebhookDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentWebhookDeliveryUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderKey sets the "provider_key" field.
func (u *PaymentWebhookDeliveryUpsertOne) SetProviderKey(v string) *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetProviderKey(v)
	})
}

// UpdateProviderKey sets the "provider_key" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertOne) UpdateProviderKey() *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateProviderKey()
	})
}

// SetDeliveryID sets the "delivery_id" field.
func (u *PaymentWebhookDeliveryUpsertOne) SetDeliveryID(v string) *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetDeliveryID(v)
	})
}

// UpdateDeliveryID sets the "delivery_id" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertOne) UpdateDeliveryID() *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateDeliveryID()
	})
}

// SetEventType sets the "event_type" field.
func (u *PaymentWebhookDeliveryUpsertOne) SetEventType(v string) *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertOne) UpdateEventType() *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateEventType()
	})
}

// SetTestNotification sets the "test_notification" field.
func (u *PaymentWebhookDeliveryUpsertOne) SetTestNotification(v bool) *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetTestNotification(v)
	})
}

// UpdateTestNotification sets the "test_notification" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertOne) UpdateTestNotification() *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateTestNotification()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentWebhookDeliveryUpsertOne) SetStatus(v string) *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertOne) UpdateStatus() *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateStatus()
	})
}

// SetRawBodyHash sets the "raw_body_hash" field.
func (u *PaymentWebhookDeliveryUpsertOne) SetRawBodyHash(v string) *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetRawBodyHash(v)
	})
}

// UpdateRawBodyHash sets the "raw_body_hash" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertOne) UpdateRawBodyHash() *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateRawBodyHash()
	})
}

// SetError sets the "error" field.
func (u *PaymentWebhookDeliveryUpsertOne) SetError(v string) *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertOne) UpdateError() *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *PaymentWebhookDeliveryUpsertOne) ClearError() *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.ClearError()
	})
}

// SetReceivedAt sets the "received_at" field.
func (u *PaymentWebhookDeliveryUpsertOne) SetReceivedAt(v time.Time) *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetReceivedAt(v)
	})
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertOne) UpdateReceivedAt() *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateReceivedAt()
	})
}

// SetProcessedAt sets the "processed_at" field.
func (u *PaymentWebhookDeliveryUpsertOne) SetProcessedAt(v time.Time) *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetProcessedAt(v)
	})
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertOne) UpdateProcessedAt() *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateProcessedAt()
	})
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *PaymentWebhookDeliveryUpsertOne) ClearProcessedAt() *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.ClearProcessedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentWebhookDeliveryUpsertOne) SetUpdatedAt(v time.Time) *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertOne) UpdateUpdatedAt() *PaymentWebhookDeliveryUpsertOne {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentWebhookDeliveryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentWebhookDeliveryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentWebhookDeliveryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentWebhookDeliveryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentWebhookDeliveryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentWebhookDeliveryCreateBulk is the builder for creating many PaymentWebhookDelivery entities in bulk.
type PaymentWebhookDeliveryCreateBulk struct {
	config
	err      error
	builders []*PaymentWebhookDeliveryCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentWebhookDelivery entities in the database.
func (_c *PaymentWebhookDeliveryCreateBulk) Save(ctx context.Context) ([]*PaymentWebhookDelivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentWebhookDelivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentWebhookDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentWebhookDeliveryCreateBulk) SaveX(ctx context.Context) []*PaymentWebhookDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentWebhookDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentWebhookDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentWebhookDelivery.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentWebhookDeliveryUpsert) {
//			SetProviderKey(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentWebhookDeliveryCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentWebhookDeliveryUpsertBulk {
	_c.conflict = opts
	return &PaymentWebhookDeliveryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentWebhookDelivery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentWebhookDeliveryCreateBulk) OnConflictColumns(columns ...string) *PaymentWebhookDeliveryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentWebhookDeliveryUpsertBulk{
		create: _c,
	}
}

// PaymentWebhookDeliveryUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentWebhookDelivery nodes.
type PaymentWebhookDeliveryUpsertBulk struct {
	create *PaymentWebhookDeliveryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentWebhookDelivery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentWebhookDeliveryUpsertBulk) UpdateNewValues() *PaymentWebhookDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentwebhookdelivery.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentWebhookDelivery.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentWebhookDeliveryUpsertBulk) Ignore() *PaymentWebhookDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentWebhookDeliveryUpsertBulk) DoNothing() *PaymentWebhookDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentWebhookDeliveryCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentWebhookDeliveryUpsertBulk) Update(set func(*PaymentWebhookDeliveryUpsert)) *PaymentWebhookDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentWebhookDeliveryUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderKey sets the "provider_key" field.
func (u *PaymentWebhookDeliveryUpsertBulk) SetProviderKey(v string) *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetProviderKey(v)
	})
}

// UpdateProviderKey sets the "provider_key" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertBulk) UpdateProviderKey() *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateProviderKey()
	})
}

// SetDeliveryID sets the "delivery_id" field.
func (u *PaymentWebhookDeliveryUpsertBulk) SetDeliveryID(v string) *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetDeliveryID(v)
	})
}

// UpdateDeliveryID sets the "delivery_id" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertBulk) UpdateDeliveryID() *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateDeliveryID()
	})
}

// SetEventType sets the "event_type" field.
func (u *PaymentWebhookDeliveryUpsertBulk) SetEventType(v string) *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertBulk) UpdateEventType() *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateEventType()
	})
}

// SetTestNotification sets the "test_notification" field.
func (u *PaymentWebhookDeliveryUpsertBulk) SetTestNotification(v bool) *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetTestNotification(v)
	})
}

// UpdateTestNotification sets the "test_notification" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertBulk) UpdateTestNotification() *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateTestNotification()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentWebhookDeliveryUpsertBulk) SetStatus(v string) *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertBulk) UpdateStatus() *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateStatus()
	})
}

// SetRawBodyHash sets the "raw_body_hash" field.
func (u *PaymentWebhookDeliveryUpsertBulk) SetRawBodyHash(v string) *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetRawBodyHash(v)
	})
}

// UpdateRawBodyHash sets the "raw_body_hash" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertBulk) UpdateRawBodyHash() *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateRawBodyHash()
	})
}

// SetError sets the "error" field.
func (u *PaymentWebhookDeliveryUpsertBulk) SetError(v string) *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertBulk) UpdateError() *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *PaymentWebhookDeliveryUpsertBulk) ClearError() *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.ClearError()
	})
}

// SetReceivedAt sets the "received_at" field.
func (u *PaymentWebhookDeliveryUpsertBulk) SetReceivedAt(v time.Time) *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetReceivedAt(v)
	})
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertBulk) UpdateReceivedAt() *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateReceivedAt()
	})
}

// SetProcessedAt sets the "processed_at" field.
func (u *PaymentWebhookDeliveryUpsertBulk) SetProcessedAt(v time.Time) *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetProcessedAt(v)
	})
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertBulk) UpdateProcessedAt() *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateProcessedAt()
	})
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *PaymentWebhookDeliveryUpsertBulk) ClearProcessedAt() *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.ClearProcessedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentWebhookDeliveryUpsertBulk) SetUpdatedAt(v time.Time) *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentWebhookDeliveryUpsertBulk) UpdateUpdatedAt() *PaymentWebhookDeliveryUpsertBulk {
	return u.Update(func(s *PaymentWebhookDeliveryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentWebhookDeliveryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentWebhookDeliveryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentWebhookDeliveryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentWebhookDeliveryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
