// Code generated by ent, DO NOT EDIT.

package paymentproviderwebhooksubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentproviderwebhooksubscription type in the database.
	Label = "payment_provider_webhook_subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProviderInstanceID holds the string denoting the provider_instance_id field in the database.
	FieldProviderInstanceID = "provider_instance_id"
	// FieldProviderKey holds the string denoting the provider_key field in the database.
	FieldProviderKey = "provider_key"
	// FieldExternalSubscriptionID holds the string denoting the external_subscription_id field in the database.
	FieldExternalSubscriptionID = "external_subscription_id"
	// FieldTriggerOn holds the string denoting the trigger_on field in the database.
	FieldTriggerOn = "trigger_on"
	// FieldDeliveryVersion holds the string denoting the delivery_version field in the database.
	FieldDeliveryVersion = "delivery_version"
	// FieldDeliveryURL holds the string denoting the delivery_url field in the database.
	FieldDeliveryURL = "delivery_url"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldSyncedAt holds the string denoting the synced_at field in the database.
	FieldSyncedAt = "synced_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the paymentproviderwebhooksubscription in the database.
	Table = "payment_provider_webhook_subscriptions"
)

// Columns holds all SQL columns for paymentproviderwebhooksubscription fields.
var Columns = []string{
	FieldID,
	FieldProviderInstanceID,
	FieldProviderKey,
	FieldExternalSubscriptionID,
	FieldTriggerOn,
	FieldDeliveryVersion,
	FieldDeliveryURL,
	FieldStatus,
	FieldLastError,
	FieldSyncedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderKeyValidator is a validator for the "provider_key" field. It is called by the builders before save.
	ProviderKeyValidator func(string) error
	// DefaultExternalSubscriptionID holds the default value on creation for the "external_subscription_id" field.
	DefaultExternalSubscriptionID string
	// ExternalSubscriptionIDValidator is a validator for the "external_subscription_id" field. It is called by the builders before save.
	ExternalSubscriptionIDValidator func(string) error
	// TriggerOnValidator is a validator for the "trigger_on" field. It is called by the builders before save.
	TriggerOnValidator func(string) error
	// DeliveryVersionValidator is a validator for the "delivery_version" field. It is called by the builders before save.
	DeliveryVersionValidator func(string) error
	// DeliveryURLValidator is a validator for the "delivery_url" field. It is called by the builders before save.
	DeliveryURLValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentProviderWebhookSubscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProviderInstanceID orders the results by the provider_instance_id field.
func ByProviderInstanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderInstanceID, opts...).ToFunc()
}

// ByProviderKey orders the results by the provider_key field.
func ByProviderKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderKey, opts...).ToFunc()
}

// ByExternalSubscriptionID orders the results by the external_subscription_id field.
func ByExternalSubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalSubscriptionID, opts...).ToFunc()
}

// ByTriggerOn orders the results by the trigger_on field.
func ByTriggerOn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerOn, opts...).ToFunc()
}

// ByDeliveryVersion orders the results by the delivery_version field.
func ByDeliveryVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryVersion, opts...).ToFunc()
}

// ByDeliveryURL orders the results by the delivery_url field.
func ByDeliveryURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryURL, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// BySyncedAt orders the results by the synced_at field.
func BySyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
