// Code generated by ent, DO NOT EDIT.

package paymentproviderwebhooksubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLTE(FieldID, id))
}

// ProviderInstanceID applies equality check predicate on the "provider_instance_id" field. It's identical to ProviderInstanceIDEQ.
func ProviderInstanceID(v int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldProviderInstanceID, v))
}

// ProviderKey applies equality check predicate on the "provider_key" field. It's identical to ProviderKeyEQ.
func ProviderKey(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldProviderKey, v))
}

// ExternalSubscriptionID applies equality check predicate on the "external_subscription_id" field. It's identical to ExternalSubscriptionIDEQ.
func ExternalSubscriptionID(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldExternalSubscriptionID, v))
}

// TriggerOn applies equality check predicate on the "trigger_on" field. It's identical to TriggerOnEQ.
func TriggerOn(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldTriggerOn, v))
}

// DeliveryVersion applies equality check predicate on the "delivery_version" field. It's identical to DeliveryVersionEQ.
func DeliveryVersion(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldDeliveryVersion, v))
}

// DeliveryURL applies equality check predicate on the "delivery_url" field. It's identical to DeliveryURLEQ.
func DeliveryURL(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldDeliveryURL, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldStatus, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldLastError, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderInstanceIDEQ applies the EQ predicate on the "provider_instance_id" field.
func ProviderInstanceIDEQ(v int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldProviderInstanceID, v))
}

// ProviderInstanceIDNEQ applies the NEQ predicate on the "provider_instance_id" field.
func ProviderInstanceIDNEQ(v int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNEQ(FieldProviderInstanceID, v))
}

// ProviderInstanceIDIn applies the In predicate on the "provider_instance_id" field.
func ProviderInstanceIDIn(vs ...int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIn(FieldProviderInstanceID, vs...))
}

// ProviderInstanceIDNotIn applies the NotIn predicate on the "provider_instance_id" field.
func ProviderInstanceIDNotIn(vs ...int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotIn(FieldProviderInstanceID, vs...))
}

// ProviderInstanceIDGT applies the GT predicate on the "provider_instance_id" field.
func ProviderInstanceIDGT(v int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGT(FieldProviderInstanceID, v))
}

// ProviderInstanceIDGTE applies the GTE predicate on the "provider_instance_id" field.
func ProviderInstanceIDGTE(v int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGTE(FieldProviderInstanceID, v))
}

// ProviderInstanceIDLT applies the LT predicate on the "provider_instance_id" field.
func ProviderInstanceIDLT(v int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLT(FieldProviderInstanceID, v))
}

// ProviderInstanceIDLTE applies the LTE predicate on the "provider_instance_id" field.
func ProviderInstanceIDLTE(v int64) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLTE(FieldProviderInstanceID, v))
}

// ProviderKeyEQ applies the EQ predicate on the "provider_key" field.
func ProviderKeyEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldProviderKey, v))
}

// ProviderKeyNEQ applies the NEQ predicate on the "provider_key" field.
func ProviderKeyNEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNEQ(FieldProviderKey, v))
}

// ProviderKeyIn applies the In predicate on the "provider_key" field.
func ProviderKeyIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIn(FieldProviderKey, vs...))
}

// ProviderKeyNotIn applies the NotIn predicate on the "provider_key" field.
func ProviderKeyNotIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotIn(FieldProviderKey, vs...))
}

// ProviderKeyGT applies the GT predicate on the "provider_key" field.
func ProviderKeyGT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGT(FieldProviderKey, v))
}

// ProviderKeyGTE applies the GTE predicate on the "provider_key" field.
func ProviderKeyGTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGTE(FieldProviderKey, v))
}

// ProviderKeyLT applies the LT predicate on the "provider_key" field.
func ProviderKeyLT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLT(FieldProviderKey, v))
}

// ProviderKeyLTE applies the LTE predicate on the "provider_key" field.
func ProviderKeyLTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLTE(FieldProviderKey, v))
}

// ProviderKeyContains applies the Contains predicate on the "provider_key" field.
func ProviderKeyContains(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContains(FieldProviderKey, v))
}

// ProviderKeyHasPrefix applies the HasPrefix predicate on the "provider_key" field.
func ProviderKeyHasPrefix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasPrefix(FieldProviderKey, v))
}

// ProviderKeyHasSuffix applies the HasSuffix predicate on the "provider_key" field.
func ProviderKeyHasSuffix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasSuffix(FieldProviderKey, v))
}

// ProviderKeyEqualFold applies the EqualFold predicate on the "provider_key" field.
func ProviderKeyEqualFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEqualFold(FieldProviderKey, v))
}

// ProviderKeyContainsFold applies the ContainsFold predicate on the "provider_key" field.
func ProviderKeyContainsFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContainsFold(FieldProviderKey, v))
}

// ExternalSubscriptionIDEQ applies the EQ predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldExternalSubscriptionID, v))
}

// ExternalSubscriptionIDNEQ applies the NEQ predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDNEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNEQ(FieldExternalSubscriptionID, v))
}

// ExternalSubscriptionIDIn applies the In predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIn(FieldExternalSubscriptionID, vs...))
}

// ExternalSubscriptionIDNotIn applies the NotIn predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDNotIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotIn(FieldExternalSubscriptionID, vs...))
}

// ExternalSubscriptionIDGT applies the GT predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDGT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGT(FieldExternalSubscriptionID, v))
}

// ExternalSubscriptionIDGTE applies the GTE predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDGTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGTE(FieldExternalSubscriptionID, v))
}

// ExternalSubscriptionIDLT applies the LT predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDLT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLT(FieldExternalSubscriptionID, v))
}

// ExternalSubscriptionIDLTE applies the LTE predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDLTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLTE(FieldExternalSubscriptionID, v))
}

// ExternalSubscriptionIDContains applies the Contains predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDContains(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContains(FieldExternalSubscriptionID, v))
}

// ExternalSubscriptionIDHasPrefix applies the HasPrefix predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDHasPrefix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasPrefix(FieldExternalSubscriptionID, v))
}

// ExternalSubscriptionIDHasSuffix applies the HasSuffix predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDHasSuffix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasSuffix(FieldExternalSubscriptionID, v))
}

// ExternalSubscriptionIDEqualFold applies the EqualFold predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDEqualFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEqualFold(FieldExternalSubscriptionID, v))
}

// ExternalSubscriptionIDContainsFold applies the ContainsFold predicate on the "external_subscription_id" field.
func ExternalSubscriptionIDContainsFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContainsFold(FieldExternalSubscriptionID, v))
}

// TriggerOnEQ applies the EQ predicate on the "trigger_on" field.
func TriggerOnEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldTriggerOn, v))
}

// TriggerOnNEQ applies the NEQ predicate on the "trigger_on" field.
func TriggerOnNEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNEQ(FieldTriggerOn, v))
}

// TriggerOnIn applies the In predicate on the "trigger_on" field.
func TriggerOnIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIn(FieldTriggerOn, vs...))
}

// TriggerOnNotIn applies the NotIn predicate on the "trigger_on" field.
func TriggerOnNotIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotIn(FieldTriggerOn, vs...))
}

// TriggerOnGT applies the GT predicate on the "trigger_on" field.
func TriggerOnGT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGT(FieldTriggerOn, v))
}

// TriggerOnGTE applies the GTE predicate on the "trigger_on" field.
func TriggerOnGTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGTE(FieldTriggerOn, v))
}

// TriggerOnLT applies the LT predicate on the "trigger_on" field.
func TriggerOnLT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLT(FieldTriggerOn, v))
}

// TriggerOnLTE applies the LTE predicate on the "trigger_on" field.
func TriggerOnLTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLTE(FieldTriggerOn, v))
}

// TriggerOnContains applies the Contains predicate on the "trigger_on" field.
func TriggerOnContains(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContains(FieldTriggerOn, v))
}

// TriggerOnHasPrefix applies the HasPrefix predicate on the "trigger_on" field.
func TriggerOnHasPrefix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasPrefix(FieldTriggerOn, v))
}

// TriggerOnHasSuffix applies the HasSuffix predicate on the "trigger_on" field.
func TriggerOnHasSuffix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasSuffix(FieldTriggerOn, v))
}

// TriggerOnEqualFold applies the EqualFold predicate on the "trigger_on" field.
func TriggerOnEqualFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEqualFold(FieldTriggerOn, v))
}

// TriggerOnContainsFold applies the ContainsFold predicate on the "trigger_on" field.
func TriggerOnContainsFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContainsFold(FieldTriggerOn, v))
}

// DeliveryVersionEQ applies the EQ predicate on the "delivery_version" field.
func DeliveryVersionEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldDeliveryVersion, v))
}

// DeliveryVersionNEQ applies the NEQ predicate on the "delivery_version" field.
func DeliveryVersionNEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNEQ(FieldDeliveryVersion, v))
}

// DeliveryVersionIn applies the In predicate on the "delivery_version" field.
func DeliveryVersionIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIn(FieldDeliveryVersion, vs...))
}

// DeliveryVersionNotIn applies the NotIn predicate on the "delivery_version" field.
func DeliveryVersionNotIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotIn(FieldDeliveryVersion, vs...))
}

// DeliveryVersionGT applies the GT predicate on the "delivery_version" field.
func DeliveryVersionGT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGT(FieldDeliveryVersion, v))
}

// DeliveryVersionGTE applies the GTE predicate on the "delivery_version" field.
func DeliveryVersionGTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGTE(FieldDeliveryVersion, v))
}

// DeliveryVersionLT applies the LT predicate on the "delivery_version" field.
func DeliveryVersionLT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLT(FieldDeliveryVersion, v))
}

// DeliveryVersionLTE applies the LTE predicate on the "delivery_version" field.
func DeliveryVersionLTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLTE(FieldDeliveryVersion, v))
}

// DeliveryVersionContains applies the Contains predicate on the "delivery_version" field.
func DeliveryVersionContains(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContains(FieldDeliveryVersion, v))
}

// DeliveryVersionHasPrefix applies the HasPrefix predicate on the "delivery_version" field.
func DeliveryVersionHasPrefix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasPrefix(FieldDeliveryVersion, v))
}

// DeliveryVersionHasSuffix applies the HasSuffix predicate on the "delivery_version" field.
func DeliveryVersionHasSuffix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasSuffix(FieldDeliveryVersion, v))
}

// DeliveryVersionEqualFold applies the EqualFold predicate on the "delivery_version" field.
func DeliveryVersionEqualFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEqualFold(FieldDeliveryVersion, v))
}

// DeliveryVersionContainsFold applies the ContainsFold predicate on the "delivery_version" field.
func DeliveryVersionContainsFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContainsFold(FieldDeliveryVersion, v))
}

// DeliveryURLEQ applies the EQ predicate on the "delivery_url" field.
func DeliveryURLEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldDeliveryURL, v))
}

// DeliveryURLNEQ applies the NEQ predicate on the "delivery_url" field.
func DeliveryURLNEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNEQ(FieldDeliveryURL, v))
}

// DeliveryURLIn applies the In predicate on the "delivery_url" field.
func DeliveryURLIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIn(FieldDeliveryURL, vs...))
}

// DeliveryURLNotIn applies the NotIn predicate on the "delivery_url" field.
func DeliveryURLNotIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotIn(FieldDeliveryURL, vs...))
}

// DeliveryURLGT applies the GT predicate on the "delivery_url" field.
func DeliveryURLGT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGT(FieldDeliveryURL, v))
}

// DeliveryURLGTE applies the GTE predicate on the "delivery_url" field.
func DeliveryURLGTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGTE(FieldDeliveryURL, v))
}

// DeliveryURLLT applies the LT predicate on the "delivery_url" field.
func DeliveryURLLT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLT(FieldDeliveryURL, v))
}

// DeliveryURLLTE applies the LTE predicate on the "delivery_url" field.
func DeliveryURLLTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLTE(FieldDeliveryURL, v))
}

// DeliveryURLContains applies the Contains predicate on the "delivery_url" field.
func DeliveryURLContains(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContains(FieldDeliveryURL, v))
}

// DeliveryURLHasPrefix applies the HasPrefix predicate on the "delivery_url" field.
func DeliveryURLHasPrefix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasPrefix(FieldDeliveryURL, v))
}

// DeliveryURLHasSuffix applies the HasSuffix predicate on the "delivery_url" field.
func DeliveryURLHasSuffix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasSuffix(FieldDeliveryURL, v))
}

// DeliveryURLEqualFold applies the EqualFold predicate on the "delivery_url" field.
func DeliveryURLEqualFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEqualFold(FieldDeliveryURL, v))
}

// DeliveryURLContainsFold applies the ContainsFold predicate on the "delivery_url" field.
func DeliveryURLContainsFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContainsFold(FieldDeliveryURL, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContainsFold(FieldStatus, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldContainsFold(FieldLastError, v))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLTE(FieldSyncedAt, v))
}

// SyncedAtIsNil applies the IsNil predicate on the "synced_at" field.
func SyncedAtIsNil() predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIsNull(FieldSyncedAt))
}

// SyncedAtNotNil applies the NotNil predicate on the "synced_at" field.
func SyncedAtNotNil() predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotNull(FieldSyncedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentProviderWebhookSubscription) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentProviderWebhookSubscription) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentProviderWebhookSubscription) predicate.PaymentProviderWebhookSubscription {
	return predicate.PaymentProviderWebhookSubscription(sql.NotPredicates(p))
}
